// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Coins {
        
        private CoinsProductType productTypeField;
        
    public CoinsProductType ProductType {get; set;}

        
        public Coins() {
            this.productTypeField = new CoinsProductType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Bullion {
        
        private List<string> modelYearField;
        
        private string mintMarkField;
        
        private string denominationUnitField;
        
        private string seriesTitleField;
        
        private string varietyField;
        
        private string subVarietyField;
        
        private string itemStylingField;
        
        private string gradedByField;
        
        private string gradeRatingField;
        
        private string certificateNumberField;
        
        private string unitGroupingField;
        
        private string eachUnitCountField;
        
        private string styleNameField;
        
        private string designationField;
        
        private string edgeStyleField;
        
        private string designerField;
        
        private string artistIDField;
        
        private string estatePeriodField;
        
        private decimal unitCointField;
        
        private bool unitCointFieldSpecified;
        
        private string materialTypeField;
        
        private LengthDimension itemDiameterField;
        
        private WeightDimension totalMetalWeightField;
        
        private string metalStampField;
        
        private string countryOfOriginField;
        
        private string labelDescriptionField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MintMark {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DenominationUnit {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SeriesTitle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Variety {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubVariety {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemStyling {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GradedBy {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GradeRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateNumber {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string UnitGrouping {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string EachUnitCount {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StyleName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Designation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EdgeStyle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Designer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtistID {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EstatePeriod {get; set;}

    public decimal UnitCoint {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitCointSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MaterialType {get; set;}

    public LengthDimension ItemDiameter {get; set;}

    public WeightDimension TotalMetalWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MetalStamp {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LabelDescription {get; set;}

        
        public Bullion() {
            this.modelYearField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ModelYear", DataType="positiveInteger")]
        public List<string> ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Coin {
        
        private List<string> modelYearField;
        
        private string mintMarkField;
        
        private string denominationUnitField;
        
        private string seriesTitleField;
        
        private string varietyField;
        
        private string subVarietyField;
        
        private string itemStylingField;
        
        private string gradedByField;
        
        private string gradeRatingField;
        
        private string certificateNumberField;
        
        private string unitGroupingField;
        
        private string eachUnitCountField;
        
        private string styleNameField;
        
        private string designationField;
        
        private string edgeStyleField;
        
        private string designerField;
        
        private string artistIDField;
        
        private string estatePeriodField;
        
        private decimal unitCointField;
        
        private bool unitCointFieldSpecified;
        
        private string materialTypeField;
        
        private LengthDimension itemDiameterField;
        
        private WeightDimension totalMetalWeightField;
        
        private string metalStampField;
        
        private string countryOfOriginField;
        
        private string labelDescriptionField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MintMark {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DenominationUnit {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SeriesTitle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Variety {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubVariety {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemStyling {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GradedBy {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GradeRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateNumber {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string UnitGrouping {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string EachUnitCount {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StyleName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Designation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EdgeStyle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Designer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtistID {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EstatePeriod {get; set;}

    public decimal UnitCoint {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitCointSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MaterialType {get; set;}

    public LengthDimension ItemDiameter {get; set;}

    public WeightDimension TotalMetalWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MetalStamp {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LabelDescription {get; set;}

        
        public Coin() {
            this.modelYearField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ModelYear", DataType="positiveInteger")]
        public List<string> ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CollectibleCoins {
        
        private List<string> modelYearField;
        
        private string mintMarkField;
        
        private string denominationUnitField;
        
        private string seriesTitleField;
        
        private string varietyField;
        
        private string subVarietyField;
        
        private string itemStylingField;
        
        private string gradedByField;
        
        private string gradeRatingField;
        
        private string certificateNumberField;
        
        private string unitGroupingField;
        
        private string eachUnitCountField;
        
        private string styleNameField;
        
        private string designationField;
        
        private string edgeStyleField;
        
        private string designerField;
        
        private string artistIDField;
        
        private string estatePeriodField;
        
        private decimal unitCointField;
        
        private bool unitCointFieldSpecified;
        
        private string materialTypeField;
        
        private LengthDimension itemDiameterField;
        
        private WeightDimension totalMetalWeightField;
        
        private string metalStampField;
        
        private string countryOfOriginField;
        
        private string labelDescriptionField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MintMark {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DenominationUnit {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SeriesTitle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Variety {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubVariety {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemStyling {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GradedBy {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GradeRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateNumber {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string UnitGrouping {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string EachUnitCount {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StyleName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Designation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EdgeStyle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Designer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtistID {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EstatePeriod {get; set;}

    public decimal UnitCoint {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitCointSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MaterialType {get; set;}

    public LengthDimension ItemDiameter {get; set;}

    public WeightDimension TotalMetalWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MetalStamp {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LabelDescription {get; set;}

        
        public CollectibleCoins() {
            this.modelYearField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ModelYear", DataType="positiveInteger")]
        public List<string> ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
            }
        }
    }
}
