// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class EUCompliance {
        
        private List<string> euLabelingHazardField;
        
        private List<string> euLabelingPrecautionaryField;
        
        private List<string> euLabelingRiskField;
        
        private List<string> euLabelingSafetyField;
        
        private WeightDimension lithiumBatteryWeightField;
        
    public WeightDimension LithiumBatteryWeight {get; set;}

        
        public EUCompliance() {
            this.euLabelingSafetyField = new List<string>();
            this.euLabelingRiskField = new List<string>();
            this.euLabelingPrecautionaryField = new List<string>();
            this.euLabelingHazardField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EuLabelingHazard")]
        public List<string> EuLabelingHazard {
            get {
                return this.euLabelingHazardField;
            }
            set {
                this.euLabelingHazardField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EuLabelingPrecautionary")]
        public List<string> EuLabelingPrecautionary {
            get {
                return this.euLabelingPrecautionaryField;
            }
            set {
                this.euLabelingPrecautionaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EuLabelingRisk")]
        public List<string> EuLabelingRisk {
            get {
                return this.euLabelingRiskField;
            }
            set {
                this.euLabelingRiskField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EuLabelingSafety")]
        public List<string> EuLabelingSafety {
            get {
                return this.euLabelingSafetyField;
            }
            set {
                this.euLabelingSafetyField = value;
            }
        }
    }
}
