// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LargeAppliances {
        
        private LargeAppliancesProductType productTypeField;
        
        private Battery batteryField;
        
        private BatteryLifeDimension batteryLifeField;
        
        private VolumeDimension capacityField;
        
        private ColorSpecification colorSpecificationField;
        
        private string countryOfOriginField;
        
        private LengthDimension diameterField;
        
        private decimal efficiencyField;
        
        private bool efficiencyFieldSpecified;
        
        private EnergyConsumptionDimension energyConsumptionField;
        
        private string formFactorField;
        
        private List<string> includedComponentsField;
        
        private string installationTypeField;
        
        private LengthDimension itemThicknessField;
        
        private string lithiumBatteryEnergyContentField;
        
        private bool lithiumBatteryPackagingFieldSpecified;
        
        private string lithiumBatteryVoltageField;
        
        private string lithiumBatteryWeightField;
        
        private string manufacturerField;
        
        private string mfrPartNumberField;
        
        private NoiseLevelDimension noiseLevelField;
        
        private string numberOfLithiumIonCellsField;
        
        private string numberOfLithiumMetalCellsField;
        
        private LargeAppliancesVariationData variationDataField;
        
        private string productGradeField;
        
        private string productNameField;
        
        private string sellerWarrantyDescriptionField;
        
        private string sidePanelColorField;
        
        private string sizeField;
        
        private List<string> specialFeaturesField;
        
        private string specificationsMetField;
        
        private VoltageDecimalDimension voltageField;
        
        private string warrantyField;
        
        private WattageDimension wattageField;
        
    public LargeAppliancesProductType ProductType {get; set;}

    public Battery Battery {get; set;}

    public BatteryLifeDimension BatteryLife {get; set;}

    public VolumeDimension Capacity {get; set;}

    public ColorSpecification ColorSpecification {get; set;}

    public string CountryOfOrigin {get; set;}

    public LengthDimension Diameter {get; set;}

    public decimal Efficiency {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EfficiencySpecified {get; set;}

    public EnergyConsumptionDimension EnergyConsumption {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FormFactor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string InstallationType {get; set;}

    public LengthDimension ItemThickness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryEnergyContent {get; set;}

    public LargeAppliancesLithiumBatteryPackaging LithiumBatteryPackaging {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryPackagingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryVoltage {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Manufacturer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfrPartNumber {get; set;}

    public NoiseLevelDimension NoiseLevel {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumIonCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumMetalCells {get; set;}

    public LargeAppliancesVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ProductGrade {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ProductName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SellerWarrantyDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SidePanelColor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Size {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecificationsMet {get; set;}

    public VoltageDecimalDimension Voltage {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Warranty {get; set;}

    public WattageDimension Wattage {get; set;}

        
        public LargeAppliances() {
            this.wattageField = new WattageDimension();
            this.voltageField = new VoltageDecimalDimension();
            this.specialFeaturesField = new List<string>();
            this.variationDataField = new LargeAppliancesVariationData();
            this.noiseLevelField = new NoiseLevelDimension();
            this.includedComponentsField = new List<string>();
            this.energyConsumptionField = new EnergyConsumptionDimension();
            this.capacityField = new VolumeDimension();
            this.batteryLifeField = new BatteryLifeDimension();
            this.productTypeField = new LargeAppliancesProductType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("IncludedComponents", DataType="normalizedString")]
        public List<string> IncludedComponents {
            get {
                return this.includedComponentsField;
            }
            set {
                this.includedComponentsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecialFeatures", DataType="normalizedString")]
        public List<string> SpecialFeatures {
            get {
                return this.specialFeaturesField;
            }
            set {
                this.specialFeaturesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CookingOven {
        
        private string burnerTypeField;
        
        private List<string> drawerTypeField;
        
        private string fuelTypeField;
        
        private string heatingElementsField;
        
        private string heatingModeField;
        
        private MaxEnergyOutputDimension maxEnergyOutputField;
        
        private string racksField;
        
        private string topStyleField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BurnerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FuelType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string HeatingElements {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HeatingMode {get; set;}

    public MaxEnergyOutputDimension MaxEnergyOutput {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Racks {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TopStyle {get; set;}

        
        public CookingOven() {
            this.maxEnergyOutputField = new MaxEnergyOutputDimension();
            this.drawerTypeField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DrawerType", DataType="normalizedString")]
        public List<string> DrawerType {
            get {
                return this.drawerTypeField;
            }
            set {
                this.drawerTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class MaxEnergyOutputDimension {
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MaxEnergyOutputUnitOfMeasure unitOfMeasure {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Cooktop {
        
        private AirflowDisplacementDimension airflowDisplacementField;
        
        private string burnerTypeField;
        
        private List<string> drawerTypeField;
        
        private string fuelTypeField;
        
        private string heatingElementsField;
        
        private MaxEnergyOutputDimension maxEnergyOutputField;
        
        private string topStyleField;
        
    public AirflowDisplacementDimension AirflowDisplacement {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BurnerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FuelType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string HeatingElements {get; set;}

    public MaxEnergyOutputDimension MaxEnergyOutput {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TopStyle {get; set;}

        
        public Cooktop() {
            this.maxEnergyOutputField = new MaxEnergyOutputDimension();
            this.drawerTypeField = new List<string>();
            this.airflowDisplacementField = new AirflowDisplacementDimension();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DrawerType", DataType="normalizedString")]
        public List<string> DrawerType {
            get {
                return this.drawerTypeField;
            }
            set {
                this.drawerTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class AirflowDisplacementDimension {
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AirflowDisplacementUnitOfMeasure unitOfMeasure {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Dishwasher {
        
        private string controlsTypeField;
        
        private LengthDimension counterDepthField;
        
        private bool isPortableField;
        
        private bool isPortableFieldSpecified;
        
        private string optionCyclesField;
        
        private string standardCyclesField;
        
        private string trayTypeField;
        
        private string washerArmsField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ControlsType {get; set;}

    public LengthDimension CounterDepth {get; set;}

    public bool IsPortable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPortableSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OptionCycles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string StandardCycles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TrayType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string WasherArms {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LaundryAppliance {
        
        private string accessLocationField;
        
        private string clothesCapacityField;
        
        private string compatibleDeviceField;
        
        private LengthDimension counterDepthField;
        
        private string dryerPowerSourceField;
        
        private bool isPortableField;
        
        private bool isPortableFieldSpecified;
        
        private RotationSpeedDimension maxRotationSpeedField;
        
        private string optionCyclesField;
        
        private string standardCyclesField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AccessLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ClothesCapacity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibleDevice {get; set;}

    public LengthDimension CounterDepth {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DryerPowerSource {get; set;}

    public bool IsPortable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPortableSpecified {get; set;}

    public RotationSpeedDimension MaxRotationSpeed {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OptionCycles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string StandardCycles {get; set;}

        
        public LaundryAppliance() {
            this.maxRotationSpeedField = new RotationSpeedDimension();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class RotationSpeedDimension {
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MaxRotationSpeedUnitOfMeasure unitOfMeasure {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MicrowaveOven {
        
        private string racksField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Racks {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Range {
        
        private AirflowDisplacementDimension airflowDisplacementField;
        
        private string burnerTypeField;
        
        private List<string> drawerTypeField;
        
        private string fuelTypeField;
        
        private string heatingElementsField;
        
        private string heatingModeField;
        
        private MaxEnergyOutputDimension maxEnergyOutputField;
        
        private string racksField;
        
        private string topStyleField;
        
    public AirflowDisplacementDimension AirflowDisplacement {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BurnerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FuelType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string HeatingElements {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HeatingMode {get; set;}

    public MaxEnergyOutputDimension MaxEnergyOutput {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Racks {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TopStyle {get; set;}

        
        public Range() {
            this.maxEnergyOutputField = new MaxEnergyOutputDimension();
            this.drawerTypeField = new List<string>();
            this.airflowDisplacementField = new AirflowDisplacementDimension();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DrawerType", DataType="normalizedString")]
        public List<string> DrawerType {
            get {
                return this.drawerTypeField;
            }
            set {
                this.drawerTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RefrigerationAppliance {
        
        private string compatibleDeviceField;
        
        private List<string> connectorTypeField;
        
        private string coolingVentsField;
        
        private LengthDimension counterDepthField;
        
        private string defrostSystemTypeField;
        
        private string doorMaterialTypeField;
        
        private object doorOrientationField;
        
        private string drawersField;
        
        private FilterPoreSizeDimension filterPoreSizeField;
        
        private VolumeDimension freezerCapacityField;
        
        private VolumeDimension freshFoodCapacityField;
        
        private IceCapacityDimension iceCapacityField;
        
        private string lightingMethodField;
        
        private string recommendedProductUsesField;
        
        private string shelfTypeField;
        
        private string shelvesField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibleDevice {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string CoolingVents {get; set;}

    public LengthDimension CounterDepth {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DefrostSystemType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DoorMaterialType {get; set;}

    public object DoorOrientation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Drawers {get; set;}

    public FilterPoreSizeDimension FilterPoreSize {get; set;}

    public VolumeDimension FreezerCapacity {get; set;}

    public VolumeDimension FreshFoodCapacity {get; set;}

    public IceCapacityDimension IceCapacity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LightingMethod {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RecommendedProductUses {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ShelfType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Shelves {get; set;}

        
        public RefrigerationAppliance() {
            this.iceCapacityField = new IceCapacityDimension();
            this.freshFoodCapacityField = new VolumeDimension();
            this.freezerCapacityField = new VolumeDimension();
            this.filterPoreSizeField = new FilterPoreSizeDimension();
            this.connectorTypeField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ConnectorType", DataType="normalizedString")]
        public List<string> ConnectorType {
            get {
                return this.connectorTypeField;
            }
            set {
                this.connectorTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class FilterPoreSizeDimension {
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FilterPoreSizeUnitOfMeasure unitOfMeasure {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class IceCapacityDimension {
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IceCapacityUnitOfMeasure unitOfMeasure {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TrashCompactor {
        
        private string compactRatioField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompactRatio {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VentHood {
        
        private AirflowDisplacementDimension airflowDisplacementField;
        
    public AirflowDisplacementDimension AirflowDisplacement {get; set;}

        
        public VentHood() {
            this.airflowDisplacementField = new AirflowDisplacementDimension();
        }
    }
}
