// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Listings {
        
        private FulfillmentOrderCancellationRequest fulfillmentOrderCancellationRequestField;
        
        private FulfillmentOrderRequest fulfillmentOrderRequestField;
        
        private Inventory inventoryField;
        
        private Item itemField;
        
        private ListingSummary listingSummaryField;
        
        private Offer offerField;
        
        private Override overrideField;
        
        private Price priceField;
        
        private Product productField;
        
        private List<ProductImage> productImageField;
        
        private Relationship relationshipField;
        
        private WebstoreItem webstoreItemField;
        
    public FulfillmentOrderCancellationRequest FulfillmentOrderCancellationRequest {get; set;}

    public FulfillmentOrderRequest FulfillmentOrderRequest {get; set;}

    public Inventory Inventory {get; set;}

    public Item Item {get; set;}

    public ListingSummary ListingSummary {get; set;}

    public Offer Offer {get; set;}

    public Override Override {get; set;}

    public Price Price {get; set;}

    public Product Product {get; set;}

    public Relationship Relationship {get; set;}

    public WebstoreItem WebstoreItem {get; set;}

        
        public Listings() {
            this.productImageField = new List<ProductImage>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ProductImage")]
        public List<ProductImage> ProductImage {
            get {
                return this.productImageField;
            }
            set {
                this.productImageField = value;
            }
        }
    }
}
