// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OrderReport {
        
        private string amazonOrderIDField;
        
        private string amazonSessionIDField;
        
        private System.DateTime orderDateField;
        
        private System.DateTime orderPostedDateField;
        
        private string marketplaceNameField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        private System.DateTime taxCalculationDateField;
        
        private bool taxCalculationDateFieldSpecified;
        
        private List<OrderReportCustomerOrderInfo> customerOrderInfoField;
        
        private OrderReportBillingData billingDataField;
        
        private OrderReportFulfillmentData fulfillmentDataField;
        
        private bool isBusinessOrderField;
        
        private bool isBusinessOrderFieldSpecified;
        
        private object purchaseOrderNumberField;
        
        private bool isPrimeField;
        
        private bool isPrimeFieldSpecified;
        
        private List<TaxAddressType> otherAddressesField;
        
        private List<OrderReportItem> itemField;
        
        private OrderReportRiskAssessmentData riskAssessmentDataField;
        
    public string AmazonOrderID {get; set;}

    public string AmazonSessionID {get; set;}

    public System.DateTime OrderDate {get; set;}

    public System.DateTime OrderPostedDate {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MarketplaceName {get; set;}

    public System.DateTime TransactionDate {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransactionDateSpecified {get; set;}

    public System.DateTime TaxCalculationDate {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxCalculationDateSpecified {get; set;}

    public OrderReportBillingData BillingData {get; set;}

    public OrderReportFulfillmentData FulfillmentData {get; set;}

    public bool IsBusinessOrder {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsBusinessOrderSpecified {get; set;}

    public object PurchaseOrderNumber {get; set;}

    public bool IsPrime {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPrimeSpecified {get; set;}

    public OrderReportRiskAssessmentData RiskAssessmentData {get; set;}

        
        public OrderReport() {
            this.riskAssessmentDataField = new OrderReportRiskAssessmentData();
            this.itemField = new List<OrderReportItem>();
            this.otherAddressesField = new List<TaxAddressType>();
            this.fulfillmentDataField = new OrderReportFulfillmentData();
            this.billingDataField = new OrderReportBillingData();
            this.customerOrderInfoField = new List<OrderReportCustomerOrderInfo>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomerOrderInfo")]
        public List<OrderReportCustomerOrderInfo> CustomerOrderInfo {
            get {
                return this.customerOrderInfoField;
            }
            set {
                this.customerOrderInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Address", IsNullable=false)]
        public List<TaxAddressType> OtherAddresses {
            get {
                return this.otherAddressesField;
            }
            set {
                this.otherAddressesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public List<OrderReportItem> Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TaxAddressType {
        
        private string cityField;
        
        private string countyField;
        
        private string stateOrRegionField;
        
        private string postalCodeField;
        
        private string postalCodeExtensionField;
        
        private string countryCodeField;
        
    public TaxAddressTypeAddressRole AddressRole {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string City {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string County {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StateOrRegion {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PostalCode {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PostalCodeExtension {get; set;}

    public string CountryCode {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TaxData {
        
        private string productTaxCodeField;
        
        private FinancialAmountsType financialAmountsField;
        
        private TaxJurisdictionType taxJurisdictionsField;
        
        private TaxDataSubtype taxableAmountsField;
        
        private TaxDataSubtype nonTaxableAmountsField;
        
        private TaxDataSubtype zeroRatedAmountsField;
        
        private TaxDataSubtype taxCollectedAmountsField;
        
        private TaxDataTaxRates taxRatesField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ProductTaxCode {get; set;}

    public FinancialAmountsType FinancialAmounts {get; set;}

    public TaxJurisdictionType TaxJurisdictions {get; set;}

    public TaxDataSubtype TaxableAmounts {get; set;}

    public TaxDataSubtype NonTaxableAmounts {get; set;}

    public TaxDataSubtype ZeroRatedAmounts {get; set;}

    public TaxDataSubtype TaxCollectedAmounts {get; set;}

    public TaxDataTaxRates TaxRates {get; set;}

        
        public TaxData() {
            this.taxRatesField = new TaxDataTaxRates();
            this.taxCollectedAmountsField = new TaxDataSubtype();
            this.zeroRatedAmountsField = new TaxDataSubtype();
            this.nonTaxableAmountsField = new TaxDataSubtype();
            this.taxableAmountsField = new TaxDataSubtype();
            this.taxJurisdictionsField = new TaxJurisdictionType();
            this.financialAmountsField = new FinancialAmountsType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class FinancialAmountsType {
        
        private FinancialAmountType displayPriceField;
        
        private CurrencyAmount taxAdjustedSellingPriceField;
        
        private FinancialAmountType extendedAmountField;
        
    public FinancialAmountType DisplayPrice {get; set;}

    public CurrencyAmount TaxAdjustedSellingPrice {get; set;}

    public FinancialAmountType ExtendedAmount {get; set;}

        
        public FinancialAmountsType() {
            this.extendedAmountField = new FinancialAmountType();
            this.displayPriceField = new FinancialAmountType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class FinancialAmountType {
        
        private CurrencyAmount amountField;
        
        private bool isTaxInclusiveField;
        
    public CurrencyAmount Amount {get; set;}

    public bool IsTaxInclusive {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TaxJurisdictionType {
        
        private string taxLocationCodeField;
        
        private string cityField;
        
        private string countyField;
        
        private string stateField;
        
        private string countryField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TaxLocationCode {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string City {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string County {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string State {get; set;}

    public string Country {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TaxDataSubtype {
        
        private CurrencyAmount districtField;
        
        private TaxDetailsType districtDetailsField;
        
        private CurrencyAmount cityField;
        
        private TaxDetailsType cityDetailsField;
        
        private CurrencyAmount countyField;
        
        private TaxDetailsType countyDetailsField;
        
        private CurrencyAmount stateField;
        
        private TaxDetailsType stateDetailsField;
        
        private CurrencyAmount countryField;
        
        private TaxDetailsType countryDetailsField;
        
    public CurrencyAmount District {get; set;}

    public TaxDetailsType DistrictDetails {get; set;}

    public CurrencyAmount City {get; set;}

    public TaxDetailsType CityDetails {get; set;}

    public CurrencyAmount County {get; set;}

    public TaxDetailsType CountyDetails {get; set;}

    public CurrencyAmount State {get; set;}

    public TaxDetailsType StateDetails {get; set;}

    public CurrencyAmount Country {get; set;}

    public TaxDetailsType CountryDetails {get; set;}

        
        public TaxDataSubtype() {
            this.countryDetailsField = new TaxDetailsType();
            this.stateDetailsField = new TaxDetailsType();
            this.countyDetailsField = new TaxDetailsType();
            this.cityDetailsField = new TaxDetailsType();
            this.districtDetailsField = new TaxDetailsType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TaxDetailsType {
        
        private string reportNameField;
        
        private string authorityTypeField;
        
        private string authorityNameField;
        
        private CurrencyAmount taxableBasisField;
        
        private CurrencyAmount nonTaxableBasisField;
        
        private string taxDirectionField;
        
        private string exemptReasonCodeField;
        
        private string buyerExemptionCertificateField;
        
        private string sellerRegistrationField;
        
        private string buyerRegistrationField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ReportName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AuthorityType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AuthorityName {get; set;}

    public CurrencyAmount TaxableBasis {get; set;}

    public CurrencyAmount NonTaxableBasis {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TaxDirection {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ExemptReasonCode {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BuyerExemptionCertificate {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SellerRegistration {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BuyerRegistration {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class TaxablePromotionType {
        
        private string promotionClaimCodeField;
        
        private string merchantPromotionIDField;
        
        private List<TaxablePromotionTypeComponent> componentField;
        
    public string PromotionClaimCode {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MerchantPromotionID {get; set;}

        
        public TaxablePromotionType() {
            this.componentField = new List<TaxablePromotionTypeComponent>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public List<TaxablePromotionTypeComponent> Component {
            get {
                return this.componentField;
            }
            set {
                this.componentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class InvoiceDataType {
        
        private string buyerSelectedInvoiceCategoryField;
        
        private string invoiceTitleField;
        
        private bool invoiceInformationFieldSpecified;
        
    public InvoiceDataTypeInvoiceRequirement InvoiceRequirement {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BuyerSelectedInvoiceCategory {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string InvoiceTitle {get; set;}

    public InvoiceDataTypeInvoiceInformation InvoiceInformation {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceInformationSpecified {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class AmazonW3CEncryptedType {
        
        private string encryptedDataField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EncryptedData {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ExpectedShipDateRangeType {
        
        private System.DateTime earliestShipDateField;
        
        private System.DateTime latestShipDateField;
        
    public System.DateTime EarliestShipDate {get; set;}

    public System.DateTime LatestShipDate {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ExpectedDeliveryDateRangeType {
        
        private System.DateTime earliestDeliveryDateField;
        
        private System.DateTime latestDeliveryDateField;
        
    public System.DateTime EarliestDeliveryDate {get; set;}

    public System.DateTime LatestDeliveryDate {get; set;}

    }
}
