// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OrderAdjustment {
        
        private string itemField;
        
        private bool actionTypeFieldSpecified;
        
        private bool cODCollectionMethodFieldSpecified;
        
        private List<OrderAdjustmentAdjustedItem> adjustedItemField;
        
    [System.Xml.Serialization.XmlElementAttribute("AmazonOrderID",typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MerchantOrderID",typeof(string),DataType="normalizedString")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {get; set;}

    public OrderAdjustmentActionType ActionType {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionTypeSpecified {get; set;}

    public OrderAdjustmentCODCollectionMethod CODCollectionMethod {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CODCollectionMethodSpecified {get; set;}

        
        public OrderAdjustment() {
            this.adjustedItemField = new List<OrderAdjustmentAdjustedItem>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AdjustedItem")]
        public List<OrderAdjustmentAdjustedItem> AdjustedItem {
            get {
                return this.adjustedItemField;
            }
            set {
                this.adjustedItemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class AdjustmentCurrencyAmount {
        
        private bool currencyFieldSpecified;
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BaseCurrencyCode currency {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool currencySpecified {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class AdjustmentBuyerPrice {
        
        private List<AdjustmentBuyerPriceComponent> componentField;
        
        public AdjustmentBuyerPrice() {
            this.componentField = new List<AdjustmentBuyerPriceComponent>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public List<AdjustmentBuyerPriceComponent> Component {
            get {
                return this.componentField;
            }
            set {
                this.componentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class AdjustmentDirectPaymentType {
        
        private List<AdjustmentDirectPaymentTypeComponent> componentField;
        
        public AdjustmentDirectPaymentType() {
            this.componentField = new List<AdjustmentDirectPaymentTypeComponent>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public List<AdjustmentDirectPaymentTypeComponent> Component {
            get {
                return this.componentField;
            }
            set {
                this.componentField = value;
            }
        }
    }
}
