// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Price {
        
        private string sKUField;
        
        private OverrideCurrencyAmount standardPriceField;
        
        private string standardPricePointsField;
        
        private decimal businessPriceField;
        
        private bool businessPriceFieldSpecified;
        
        private bool quantityPriceTypeFieldSpecified;
        
        private PriceQuantityPrice quantityPriceField;
        
        private StringOverrideCurrencyAmount minimumSellerAllowedPriceField;
        
        private StringOverrideCurrencyAmount maximumSellerAllowedPriceField;
        
        private OverrideCurrencyAmount mAPField;
        
        private CurrencyAmountWithDefault depositAmountField;
        
        private PriceSale saleField;
        
        private DatedCompareAtPrice compareAtField;
        
        private DatedPrice previousField;
        
        private PriceRental_0 rental_0Field;
        
        private PriceRental_1 rental_1Field;
        
        private PriceRental_2 rental_2Field;
        
        private PriceRental_3 rental_3Field;
        
        private PriceRental_4 rental_4Field;
        
        private PriceRental_5 rental_5Field;
        
        private PriceRental_6 rental_6Field;
        
        private PriceRental_7 rental_7Field;
        
        private PriceRental_8 rental_8Field;
        
        private PriceRental_9 rental_9Field;
        
        private OverrideCurrencyAmount costPerClickBidPriceField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SKU {get; set;}

    public OverrideCurrencyAmount StandardPrice {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string StandardPricePoints {get; set;}

    public decimal BusinessPrice {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BusinessPriceSpecified {get; set;}

    public QuantityPriceTypes QuantityPriceType {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuantityPriceTypeSpecified {get; set;}

    public PriceQuantityPrice QuantityPrice {get; set;}

    public StringOverrideCurrencyAmount MinimumSellerAllowedPrice {get; set;}

    public StringOverrideCurrencyAmount MaximumSellerAllowedPrice {get; set;}

    public OverrideCurrencyAmount MAP {get; set;}

    public CurrencyAmountWithDefault DepositAmount {get; set;}

    public PriceSale Sale {get; set;}

    public DatedCompareAtPrice CompareAt {get; set;}

    public DatedPrice Previous {get; set;}

    public PriceRental_0 Rental_0 {get; set;}

    public PriceRental_1 Rental_1 {get; set;}

    public PriceRental_2 Rental_2 {get; set;}

    public PriceRental_3 Rental_3 {get; set;}

    public PriceRental_4 Rental_4 {get; set;}

    public PriceRental_5 Rental_5 {get; set;}

    public PriceRental_6 Rental_6 {get; set;}

    public PriceRental_7 Rental_7 {get; set;}

    public PriceRental_8 Rental_8 {get; set;}

    public PriceRental_9 Rental_9 {get; set;}

    public OverrideCurrencyAmount CostPerClickBidPrice {get; set;}

        
        public Price() {
            this.costPerClickBidPriceField = new OverrideCurrencyAmount();
            this.rental_9Field = new PriceRental_9();
            this.rental_8Field = new PriceRental_8();
            this.rental_7Field = new PriceRental_7();
            this.rental_6Field = new PriceRental_6();
            this.rental_5Field = new PriceRental_5();
            this.rental_4Field = new PriceRental_4();
            this.rental_3Field = new PriceRental_3();
            this.rental_2Field = new PriceRental_2();
            this.rental_1Field = new PriceRental_1();
            this.rental_0Field = new PriceRental_0();
            this.previousField = new DatedPrice();
            this.compareAtField = new DatedCompareAtPrice();
            this.saleField = new PriceSale();
            this.depositAmountField = new CurrencyAmountWithDefault();
            this.mAPField = new OverrideCurrencyAmount();
            this.maximumSellerAllowedPriceField = new StringOverrideCurrencyAmount();
            this.minimumSellerAllowedPriceField = new StringOverrideCurrencyAmount();
            this.quantityPriceField = new PriceQuantityPrice();
            this.standardPriceField = new OverrideCurrencyAmount();
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverrideCurrencyAmountWithTax))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class OverrideCurrencyAmount : CurrencyAmountWithDefault {
        
        private bool zeroField;
        
        private bool zeroFieldSpecified;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool zero {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool zeroSpecified {get; set;}

    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverrideCurrencyAmount))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverrideCurrencyAmountWithTax))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class CurrencyAmountWithDefault {
        
        private decimal valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BaseCurrencyCodeWithDefault currency {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class OverrideCurrencyAmountWithTax : OverrideCurrencyAmount {
        
        private decimal valueWithoutTaxField;
        
        private bool valueWithoutTaxFieldSpecified;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal valueWithoutTax {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueWithoutTaxSpecified {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class StringOverrideCurrencyAmount : StringCurrencyAmountWithDefault {
        
        private bool zeroField;
        
        private bool zeroFieldSpecified;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool zero {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool zeroSpecified {get; set;}

    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringOverrideCurrencyAmount))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class StringCurrencyAmountWithDefault {
        
        private BaseCurrencyCodeWithDefault currencyField;
        
        private string valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BaseCurrencyCodeWithDefault currency {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {get; set;}

    }
}
