// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SoftwareVideoGames {
        
        private List<RebateType> rebateField;
        
        private SoftwareVideoGamesProductType productTypeField;
        
        private Battery batteryField;
        
        private WeightDimension displayWeightField;
        
        private VolumeDimension displayVolumeField;
        
        private LengthDimension displayLengthField;
        
        private string mfgWarrantyDescriptionPartsField;
        
        private string mfgWarrantyDescriptionTypeField;
        
        private string mfgWarrantyDescriptionLaborField;
        
        private List<LanguageSWVG> languageOriginalField;
        
        private List<LanguageSWVG> languageSubtitledField;
        
        private List<LanguageSWVG> languageDubbedField;
        
        private bool parentageFieldSpecified;
        
        private bool variationThemeFieldSpecified;
        
        private decimal batteryAverageLifeField;
        
        private bool batteryAverageLifeFieldSpecified;
        
        private decimal batteryAverageLifeStandbyField;
        
        private bool batteryAverageLifeStandbyFieldSpecified;
        
        private decimal batteryChargeTimeField;
        
        private bool batteryChargeTimeFieldSpecified;
        
        private bool isAdultProductField;
        
        private bool isAdultProductFieldSpecified;
        
        private string batteryTypeLithiumIonField;
        
        private string batteryTypeLithiumMetalField;
        
        private string colorNameField;
        
        private string countField;
        
        private string countryOfOriginField;
        
        private string customerPackageTypeField;
        
        private bool canShipInOriginalContainerField;
        
        private bool canShipInOriginalContainerFieldSpecified;
        
        private bool identityPackageTypeFieldSpecified;
        
        private string gappPrcDczField;
        
        private string gappPrcXcyzField;
        
        private string includedComponentsField;
        
        private decimal lithiumBatteryEnergyContentField;
        
        private bool lithiumBatteryEnergyContentFieldSpecified;
        
        private bool lithiumBatteryPackagingFieldSpecified;
        
        private decimal lithiumBatteryVoltageField;
        
        private bool lithiumBatteryVoltageFieldSpecified;
        
        private decimal lithiumBatteryWeightField;
        
        private bool lithiumBatteryWeightFieldSpecified;
        
        private string maxOrderQuantityField;
        
        private string numberOfItemsField;
        
        private string numberOfLithiumIonCellsField;
        
        private string numberOfLithiumMetalCellsField;
        
        private string powerSourceField;
        
        private string publisherField;
        
        private string publishingCompanyField;
        
        private string regionOfOriginField;
        
        private string sellerWarrantyDescriptionField;
        
        private string sizeField;
        
        private string sizeMapField;
        
        private string styleNameField;
        
        private bool targetGenderFieldSpecified;
        
        private string warningsField;
        
        private List<string> specificUsesForProductField;
        
    public SoftwareVideoGamesProductType ProductType {get; set;}

    public Battery Battery {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public LengthDimension DisplayLength {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfgWarrantyDescriptionParts {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfgWarrantyDescriptionType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfgWarrantyDescriptionLabor {get; set;}

    public SoftwareVideoGamesParentage Parentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ParentageSpecified {get; set;}

    public SoftwareVideoGamesVariationTheme VariationTheme {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VariationThemeSpecified {get; set;}

    public decimal BatteryAverageLife {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryAverageLifeSpecified {get; set;}

    public decimal BatteryAverageLifeStandby {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryAverageLifeStandbySpecified {get; set;}

    public decimal BatteryChargeTime {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryChargeTimeSpecified {get; set;}

    public bool IsAdultProduct {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsAdultProductSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BatteryTypeLithiumIon {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BatteryTypeLithiumMetal {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Count {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CustomerPackageType {get; set;}

    public bool CanShipInOriginalContainer {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CanShipInOriginalContainerSpecified {get; set;}

    public SoftwareVideoGamesIdentityPackageType IdentityPackageType {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdentityPackageTypeSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GappPrcDcz {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GappPrcXcyz {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IncludedComponents {get; set;}

    public decimal LithiumBatteryEnergyContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryEnergyContentSpecified {get; set;}

    public SoftwareVideoGamesLithiumBatteryPackaging LithiumBatteryPackaging {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryPackagingSpecified {get; set;}

    public decimal LithiumBatteryVoltage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryVoltageSpecified {get; set;}

    public decimal LithiumBatteryWeight {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryWeightSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxOrderQuantity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfItems {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumIonCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumMetalCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PowerSource {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Publisher {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PublishingCompany {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RegionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SellerWarrantyDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Size {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StyleName {get; set;}

    public SoftwareVideoGamesTargetGender TargetGender {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TargetGenderSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Warnings {get; set;}

        
        public SoftwareVideoGames() {
            this.specificUsesForProductField = new List<string>();
            this.languageDubbedField = new List<LanguageSWVG>();
            this.languageSubtitledField = new List<LanguageSWVG>();
            this.languageOriginalField = new List<LanguageSWVG>();
            this.displayVolumeField = new VolumeDimension();
            this.productTypeField = new SoftwareVideoGamesProductType();
            this.rebateField = new List<RebateType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Rebate")]
        public List<RebateType> Rebate {
            get {
                return this.rebateField;
            }
            set {
                this.rebateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LanguageOriginal")]
        public List<LanguageSWVG> LanguageOriginal {
            get {
                return this.languageOriginalField;
            }
            set {
                this.languageOriginalField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LanguageSubtitled")]
        public List<LanguageSWVG> LanguageSubtitled {
            get {
                return this.languageSubtitledField;
            }
            set {
                this.languageSubtitledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LanguageDubbed")]
        public List<LanguageSWVG> LanguageDubbed {
            get {
                return this.languageDubbedField;
            }
            set {
                this.languageDubbedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecificUsesForProduct", DataType="normalizedString")]
        public List<string> SpecificUsesForProduct {
            get {
                return this.specificUsesForProductField;
            }
            set {
                this.specificUsesForProductField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class HandheldSoftwareDownloads {
        
        private string applicationVersionField;
        
        private DownloadableFile downloadableFileField;
        
        private List<string> operatingSystemField;
        
        private string systemRequirementsField;
        
        private string numberOfLicensesField;
        
        private string maxNumberOfPlayersField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ApplicationVersion {get; set;}

    public DownloadableFile DownloadableFile {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SystemRequirements {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLicenses {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxNumberOfPlayers {get; set;}

        
        public HandheldSoftwareDownloads() {
            this.operatingSystemField = new List<string>();
            this.downloadableFileField = new DownloadableFile();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OperatingSystem", DataType="normalizedString")]
        public List<string> OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DownloadableFile {
        
        private string downloadableFileFormatField;
        
        private MemorySizeDimension fileSizeField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DownloadableFileFormat {get; set;}

    public MemorySizeDimension FileSize {get; set;}

        
        public DownloadableFile() {
            this.fileSizeField = new MemorySizeDimension();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Software {
        
        private List<string> mediaFormatField;
        
        private List<string> operatingSystemField;
        
        private string bundlesField;
        
        private List<string> childrensSoftwareGenreField;
        
        private object itemField;
        
        private List<string> eSRBDescriptorsField;
        
        private List<string> hardwarePlatformField;
        
        private PEGIDetailsType pEGIDetailsField;
        
        private string maxNumberOfPlayersField;
        
        private string mFGSuggestedAgeMinField;
        
        private string mFGSuggestedAgeMaxField;
        
        private List<SoftwarePlatform> softwarePlatformField;
        
        private string applicationVersionField;
        
        private string numberOfLicensesField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Bundles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute("BBFCRating",typeof(BBFCRatingType))]
    [System.Xml.Serialization.XmlElementAttribute("ESRBRating",typeof(string),DataType="normalizedString")]
    [System.Xml.Serialization.XmlElementAttribute("PEGIRating",typeof(PEGIRatingType))]
    [System.Xml.Serialization.XmlElementAttribute("USKRating",typeof(USKRatingType))]
    public object Item {get; set;}

    public PEGIDetailsType PEGIDetails {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxNumberOfPlayers {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MFGSuggestedAgeMin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MFGSuggestedAgeMax {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ApplicationVersion {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLicenses {get; set;}

        
        public Software() {
            this.softwarePlatformField = new List<SoftwarePlatform>();
            this.pEGIDetailsField = new PEGIDetailsType();
            this.hardwarePlatformField = new List<string>();
            this.eSRBDescriptorsField = new List<string>();
            this.childrensSoftwareGenreField = new List<string>();
            this.operatingSystemField = new List<string>();
            this.mediaFormatField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MediaFormat", DataType="normalizedString")]
        public List<string> MediaFormat {
            get {
                return this.mediaFormatField;
            }
            set {
                this.mediaFormatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OperatingSystem", DataType="normalizedString")]
        public List<string> OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ChildrensSoftwareGenre", DataType="normalizedString")]
        public List<string> ChildrensSoftwareGenre {
            get {
                return this.childrensSoftwareGenreField;
            }
            set {
                this.childrensSoftwareGenreField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ESRBDescriptors", DataType="normalizedString")]
        public List<string> ESRBDescriptors {
            get {
                return this.eSRBDescriptorsField;
            }
            set {
                this.eSRBDescriptorsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("HardwarePlatform", DataType="normalizedString")]
        public List<string> HardwarePlatform {
            get {
                return this.hardwarePlatformField;
            }
            set {
                this.hardwarePlatformField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SoftwarePlatform")]
        public List<SoftwarePlatform> SoftwarePlatform {
            get {
                return this.softwarePlatformField;
            }
            set {
                this.softwarePlatformField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PEGIDetailsType {
        
        private bool badLanguageField;
        
        private bool badLanguageFieldSpecified;
        
        private bool fearField;
        
        private bool fearFieldSpecified;
        
        private bool violenceField;
        
        private bool violenceFieldSpecified;
        
        private bool discriminationField;
        
        private bool discriminationFieldSpecified;
        
        private bool drugsField;
        
        private bool drugsFieldSpecified;
        
        private bool sexualContentField;
        
        private bool sexualContentFieldSpecified;
        
    public bool BadLanguage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BadLanguageSpecified {get; set;}

    public bool Fear {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FearSpecified {get; set;}

    public bool Violence {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ViolenceSpecified {get; set;}

    public bool Discrimination {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DiscriminationSpecified {get; set;}

    public bool Drugs {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DrugsSpecified {get; set;}

    public bool SexualContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SexualContentSpecified {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SoftwarePlatform {
        
        private string systemRequirementsField;
        
    public HardwarePlatformType HardwarePlatform {get; set;}

        
        public SoftwarePlatform() {
            this.systemRequirementsField = "N/A";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        [System.ComponentModel.DefaultValueAttribute("N/A")]
        public string SystemRequirements {
            get {
                return this.systemRequirementsField;
            }
            set {
                this.systemRequirementsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SoftwareGames {
        
        private List<string> softwareVideoGamesGenreField;
        
        private object itemField;
        
        private List<string> mediaFormatField;
        
        private List<string> operatingSystemField;
        
        private string bundlesField;
        
        private List<string> eSRBDescriptorsField;
        
        private List<string> hardwarePlatformField;
        
        private PEGIDetailsType pEGIDetailsField;
        
        private string mFGSuggestedAgeMinField;
        
        private string mFGSuggestedAgeMaxField;
        
        private string maxNumberOfPlayersField;
        
        private List<SoftwarePlatform> softwarePlatformField;
        
        private bool onlinePlayField;
        
        private bool onlinePlayFieldSpecified;
        
    [System.Xml.Serialization.XmlElementAttribute("BBFCRating",typeof(BBFCRatingType))]
    [System.Xml.Serialization.XmlElementAttribute("ESRBRating",typeof(string),DataType="normalizedString")]
    [System.Xml.Serialization.XmlElementAttribute("PEGIRating",typeof(PEGIRatingType))]
    [System.Xml.Serialization.XmlElementAttribute("USKRating",typeof(USKRatingType))]
    public object Item {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Bundles {get; set;}

    public PEGIDetailsType PEGIDetails {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MFGSuggestedAgeMin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MFGSuggestedAgeMax {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxNumberOfPlayers {get; set;}

    public bool OnlinePlay {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OnlinePlaySpecified {get; set;}

        
        public SoftwareGames() {
            this.softwarePlatformField = new List<SoftwarePlatform>();
            this.pEGIDetailsField = new PEGIDetailsType();
            this.hardwarePlatformField = new List<string>();
            this.eSRBDescriptorsField = new List<string>();
            this.operatingSystemField = new List<string>();
            this.mediaFormatField = new List<string>();
            this.softwareVideoGamesGenreField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SoftwareVideoGamesGenre", DataType="normalizedString")]
        public List<string> SoftwareVideoGamesGenre {
            get {
                return this.softwareVideoGamesGenreField;
            }
            set {
                this.softwareVideoGamesGenreField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MediaFormat", DataType="normalizedString")]
        public List<string> MediaFormat {
            get {
                return this.mediaFormatField;
            }
            set {
                this.mediaFormatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OperatingSystem", DataType="normalizedString")]
        public List<string> OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ESRBDescriptors", DataType="normalizedString")]
        public List<string> ESRBDescriptors {
            get {
                return this.eSRBDescriptorsField;
            }
            set {
                this.eSRBDescriptorsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("HardwarePlatform", DataType="normalizedString")]
        public List<string> HardwarePlatform {
            get {
                return this.hardwarePlatformField;
            }
            set {
                this.hardwarePlatformField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SoftwarePlatform")]
        public List<SoftwarePlatform> SoftwarePlatform {
            get {
                return this.softwarePlatformField;
            }
            set {
                this.softwarePlatformField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VideoGames {
        
        private List<string> consoleVideoGamesGenreField;
        
        private object itemField;
        
        private List<string> hardwarePlatformField;
        
        private string bundlesField;
        
        private List<string> eSRBDescriptorsField;
        
        private PEGIDetailsType pEGIDetailsField;
        
        private string maxNumberOfPlayersField;
        
        private string numberOfLicensesField;
        
    [System.Xml.Serialization.XmlElementAttribute("BBFCRating",typeof(BBFCRatingType))]
    [System.Xml.Serialization.XmlElementAttribute("ESRBRating",typeof(string),DataType="normalizedString")]
    [System.Xml.Serialization.XmlElementAttribute("PEGIRating",typeof(PEGIRatingType))]
    [System.Xml.Serialization.XmlElementAttribute("USKRating",typeof(USKRatingType))]
    public object Item {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Bundles {get; set;}

    public PEGIDetailsType PEGIDetails {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxNumberOfPlayers {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLicenses {get; set;}

        
        public VideoGames() {
            this.pEGIDetailsField = new PEGIDetailsType();
            this.eSRBDescriptorsField = new List<string>();
            this.hardwarePlatformField = new List<string>();
            this.consoleVideoGamesGenreField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ConsoleVideoGamesGenre", DataType="normalizedString")]
        public List<string> ConsoleVideoGamesGenre {
            get {
                return this.consoleVideoGamesGenreField;
            }
            set {
                this.consoleVideoGamesGenreField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("HardwarePlatform", DataType="normalizedString")]
        public List<string> HardwarePlatform {
            get {
                return this.hardwarePlatformField;
            }
            set {
                this.hardwarePlatformField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ESRBDescriptors", DataType="normalizedString")]
        public List<string> ESRBDescriptors {
            get {
                return this.eSRBDescriptorsField;
            }
            set {
                this.eSRBDescriptorsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VideoGamesAccessories {
        
        private List<string> hardwarePlatformField;
        
        private string bundlesField;
        
        private string colorField;
        
        private string colorMapField;
        
        private string additionalFeaturesField;
        
        private string itemPackageQuantityField;
        
        private string maxNumberOfPlayersField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Bundles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AdditionalFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string ItemPackageQuantity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxNumberOfPlayers {get; set;}

        
        public VideoGamesAccessories() {
            this.hardwarePlatformField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("HardwarePlatform", DataType="normalizedString")]
        public List<string> HardwarePlatform {
            get {
                return this.hardwarePlatformField;
            }
            set {
                this.hardwarePlatformField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VideoGamesHardware {
        
        private List<string> hardwarePlatformField;
        
        private string bundlesField;
        
        private string colorField;
        
        private string colorMapField;
        
        private string additionalFeaturesField;
        
        private string itemPackageQuantityField;
        
        private string maxNumberOfPlayersField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Bundles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AdditionalFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string ItemPackageQuantity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxNumberOfPlayers {get; set;}

        
        public VideoGamesHardware() {
            this.hardwarePlatformField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("HardwarePlatform", DataType="normalizedString")]
        public List<string> HardwarePlatform {
            get {
                return this.hardwarePlatformField;
            }
            set {
                this.hardwarePlatformField = value;
            }
        }
    }
}
