// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Wireless {
        
        private List<RebateType> rebateField;
        
        private WirelessProductType productTypeField;
        
        private string batteryTypeLithiumIonField;
        
        private string batteryTypeLithiumMetalField;
        
        private decimal lithiumBatteryEnergyContentField;
        
        private bool lithiumBatteryEnergyContentFieldSpecified;
        
        private bool lithiumBatteryPackagingFieldSpecified;
        
        private decimal lithiumBatteryVoltageField;
        
        private bool lithiumBatteryVoltageFieldSpecified;
        
        private decimal lithiumBatteryWeightField;
        
        private bool lithiumBatteryWeightFieldSpecified;
        
        private string numberOfLithiumIonCellsField;
        
        private string numberOfLithiumMetalCellsField;
        
    public WirelessProductType ProductType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BatteryTypeLithiumIon {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BatteryTypeLithiumMetal {get; set;}

    public decimal LithiumBatteryEnergyContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryEnergyContentSpecified {get; set;}

    public WirelessLithiumBatteryPackaging LithiumBatteryPackaging {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryPackagingSpecified {get; set;}

    public decimal LithiumBatteryVoltage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryVoltageSpecified {get; set;}

    public decimal LithiumBatteryWeight {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryWeightSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumIonCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumMetalCells {get; set;}

        
        public Wireless() {
            this.productTypeField = new WirelessProductType();
            this.rebateField = new List<RebateType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Rebate")]
        public List<RebateType> Rebate {
            get {
                return this.rebateField;
            }
            set {
                this.rebateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WirelessAccessories {
        
        private WirelessAccessoriesVariationData variationDataField;
        
        private string colorField;
        
        private ColorMap colorMapField;
        
        private bool colorMapFieldSpecified;
        
        private List<string> additionalFeaturesField;
        
        private TimeDimension talkTimeField;
        
        private TimeDimension standbyTimeField;
        
        private TimeDimension chargingTimeField;
        
        private BatteryPowerIntegerDimension batteryPowerField;
        
        private bool solarField;
        
        private bool solarFieldSpecified;
        
        private bool refillableField;
        
        private bool refillableFieldSpecified;
        
        private bool extendedField;
        
        private bool extendedFieldSpecified;
        
        private bool slimField;
        
        private bool slimFieldSpecified;
        
        private bool auxiliaryField;
        
        private bool auxiliaryFieldSpecified;
        
        private string batteryTypeField;
        
        private string antennaTypeField;
        
        private List<string> compatiblePhoneModelsField;
        
        private string manufacturerNameField;
        
        private List<string> keywordsField;
        
        private string itemPackageQuantityField;
        
        private bool headsetTypeFieldSpecified;
        
        private bool headsetStyleFieldSpecified;
        
    public WirelessAccessoriesVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

    public ColorMap ColorMap {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorMapSpecified {get; set;}

    public TimeDimension TalkTime {get; set;}

    public TimeDimension StandbyTime {get; set;}

    public TimeDimension ChargingTime {get; set;}

    public BatteryPowerIntegerDimension BatteryPower {get; set;}

    public bool Solar {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SolarSpecified {get; set;}

    public bool Refillable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RefillableSpecified {get; set;}

    public bool Extended {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExtendedSpecified {get; set;}

    public bool Slim {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SlimSpecified {get; set;}

    public bool Auxiliary {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AuxiliarySpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BatteryType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AntennaType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ManufacturerName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string ItemPackageQuantity {get; set;}

    public HeadsetTypeValue HeadsetType {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeadsetTypeSpecified {get; set;}

    public HeadsetStyleValue HeadsetStyle {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeadsetStyleSpecified {get; set;}

        
        public WirelessAccessories() {
            this.keywordsField = new List<string>();
            this.compatiblePhoneModelsField = new List<string>();
            this.batteryPowerField = new BatteryPowerIntegerDimension();
            this.chargingTimeField = new TimeDimension();
            this.standbyTimeField = new TimeDimension();
            this.talkTimeField = new TimeDimension();
            this.additionalFeaturesField = new List<string>();
            this.variationDataField = new WirelessAccessoriesVariationData();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalFeatures", DataType="normalizedString")]
        public List<string> AdditionalFeatures {
            get {
                return this.additionalFeaturesField;
            }
            set {
                this.additionalFeaturesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CompatiblePhoneModels", DataType="normalizedString")]
        public List<string> CompatiblePhoneModels {
            get {
                return this.compatiblePhoneModelsField;
            }
            set {
                this.compatiblePhoneModelsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Keywords", DataType="normalizedString")]
        public List<string> Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WirelessDownloads {
        
        private List<string> compatiblePhoneModelsField;
        
        private string manufacturerNameField;
        
        private string additionalFeaturesField;
        
        private List<string> keywordsField;
        
        private string applicationVersionField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ManufacturerName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AdditionalFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ApplicationVersion {get; set;}

        
        public WirelessDownloads() {
            this.keywordsField = new List<string>();
            this.compatiblePhoneModelsField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CompatiblePhoneModels", DataType="normalizedString")]
        public List<string> CompatiblePhoneModels {
            get {
                return this.compatiblePhoneModelsField;
            }
            set {
                this.compatiblePhoneModelsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Keywords", DataType="normalizedString")]
        public List<string> Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
    }
}
