// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Arts {
        
        private ArtsProductType productTypeField;
        
        private ArtsVariationData variationDataField;
        
    public ArtsProductType ProductType {get; set;}

    public ArtsVariationData VariationData {get; set;}

        
        public Arts() {
            this.variationDataField = new ArtsVariationData();
            this.productTypeField = new ArtsProductType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FineArt {
        
        private string artworkTypeField;
        
        private string artistField;
        
        private string artistBiographyField;
        
        private string artworkMediumField;
        
        private System.DateTime dateField;
        
        private string artworkSubMediumField;
        
        private string archivalGradingField;
        
        private string signedByField;
        
        private string signatureLocationField;
        
        private string certificateOfAuthenticityField;
        
        private string certificateOfAuthenticityNumberField;
        
        private string frameMaterialField;
        
        private string hangingHardwareIncludedField;
        
        private string glassTypeField;
        
        private string mattingDescriptionField;
        
        private bool framedField;
        
        private List<string> subjectField;
        
        private string subjectLocationField;
        
        private List<string> colorField;
        
        private string colorFamilyField;
        
        private bool adultField;
        
        private bool adultFieldSpecified;
        
        private List<string> styleField;
        
        private string periodField;
        
        private string exhibitionHistoryField;
        
        private string literatureField;
        
        private string provenanceField;
        
        private string countryOfOriginField;
        
        private string regionOfOriginField;
        
        private string sizeNameField;
        
        private LengthDimension framedHeightField;
        
        private LengthDimension framedWidthField;
        
        private LengthDimension framedDepthField;
        
        private string shapeField;
        
        private string orientationField;
        
        private string saleTypeField;
        
        private string isCratedField;
        
        private bool isVeryHighValueField;
        
        private bool isVeryHighValueFieldSpecified;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtworkType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Artist {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtistBiography {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtworkMedium {get; set;}

    public System.DateTime Date {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtworkSubMedium {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArchivalGrading {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SignedBy {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SignatureLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateOfAuthenticity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateOfAuthenticityNumber {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FrameMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HangingHardwareIncluded {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GlassType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MattingDescription {get; set;}

    public bool Framed {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubjectLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorFamily {get; set;}

    public bool Adult {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdultSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Period {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ExhibitionHistory {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Literature {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Provenance {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RegionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeName {get; set;}

    public LengthDimension FramedHeight {get; set;}

    public LengthDimension FramedWidth {get; set;}

    public LengthDimension FramedDepth {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Shape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Orientation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SaleType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IsCrated {get; set;}

    public bool IsVeryHighValue {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsVeryHighValueSpecified {get; set;}

        
        public FineArt() {
            this.styleField = new List<string>();
            this.colorField = new List<string>();
            this.subjectField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Subject", DataType="normalizedString")]
        public List<string> Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Color", DataType="normalizedString")]
        public List<string> Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Style", DataType="normalizedString")]
        public List<string> Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FineArtEditioned {
        
        private string artworkTypeField;
        
        private string artistField;
        
        private string artistBiographyField;
        
        private string artworkMediumField;
        
        private System.DateTime dateField;
        
        private string artworkSubMediumField;
        
        private string archivalGradingField;
        
        private string signedByField;
        
        private string signatureLocationField;
        
        private string certificateOfAuthenticityField;
        
        private string certificateOfAuthenticityNumberField;
        
        private string frameMaterialField;
        
        private string hangingHardwareIncludedField;
        
        private string glassTypeField;
        
        private string mattingDescriptionField;
        
        private bool framedField;
        
        private List<string> subjectField;
        
        private string subjectLocationField;
        
        private List<string> colorField;
        
        private string colorFamilyField;
        
        private bool adultField;
        
        private bool adultFieldSpecified;
        
        private List<string> styleField;
        
        private string periodField;
        
        private string exhibitionHistoryField;
        
        private string literatureField;
        
        private string provenanceField;
        
        private string countryOfOriginField;
        
        private string regionOfOriginField;
        
        private string limitedEditionSizeField;
        
        private string limitedEditionRangeStartField;
        
        private string limitedEditionRangeEndField;
        
        private System.DateTime printDateField;
        
        private bool printDateFieldSpecified;
        
        private string sizeNameField;
        
        private LengthDimension framedHeightField;
        
        private LengthDimension framedWidthField;
        
        private LengthDimension framedDepthField;
        
        private string shapeField;
        
        private string orientationField;
        
        private string saleTypeField;
        
        private string isCratedField;
        
        private bool isVeryHighValueField;
        
        private bool isVeryHighValueFieldSpecified;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtworkType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Artist {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtistBiography {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtworkMedium {get; set;}

    public System.DateTime Date {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtworkSubMedium {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArchivalGrading {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SignedBy {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SignatureLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateOfAuthenticity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CertificateOfAuthenticityNumber {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FrameMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HangingHardwareIncluded {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string GlassType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MattingDescription {get; set;}

    public bool Framed {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubjectLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorFamily {get; set;}

    public bool Adult {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdultSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Period {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ExhibitionHistory {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Literature {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Provenance {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RegionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LimitedEditionSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LimitedEditionRangeStart {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LimitedEditionRangeEnd {get; set;}

    public System.DateTime PrintDate {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrintDateSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeName {get; set;}

    public LengthDimension FramedHeight {get; set;}

    public LengthDimension FramedWidth {get; set;}

    public LengthDimension FramedDepth {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Shape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Orientation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SaleType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IsCrated {get; set;}

    public bool IsVeryHighValue {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsVeryHighValueSpecified {get; set;}

        
        public FineArtEditioned() {
            this.styleField = new List<string>();
            this.colorField = new List<string>();
            this.subjectField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Subject", DataType="normalizedString")]
        public List<string> Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Color", DataType="normalizedString")]
        public List<string> Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Style", DataType="normalizedString")]
        public List<string> Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
    }
}
