// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Baby {
        
        private BabyProductType productTypeField;
        
    public BabyProductType ProductType {get; set;}

        
        public Baby() {
            this.productTypeField = new BabyProductType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BabyProducts {
        
        private string alertTypeField;
        
        private string assemblyInstructionsField;
        
        private AssemblyTimeDimension assemblyTimeField;
        
        private string awardsWonField;
        
        private string baseTypeField;
        
        private LengthDimension baseWidthField;
        
        private Battery batteryField;
        
        private BatteryLifeDimension batteryAverageLifeField;
        
        private BatteryLifeDimension batteryAverageLifeStandbyField;
        
        private TimeDimension batteryAverageLifeTalkTimeField;
        
        private BatteryPowerDimension batteryCapacityField;
        
        private bool batteryCellCompositionFieldSpecified;
        
        private TimeDimension batteryChargeTimeField;
        
        private string batteryDescriptionField;
        
        private BatteryPowerIntegerDimension batteryPowerField;
        
        private string bottleNippleTypeField;
        
        private string bottleTypeField;
        
        private List<string> careInstructionsField;
        
        private WeightDimension carrierWeightField;
        
        private List<CarSeatWeightGroupEUType> carSeatWeightGroupEUField;
        
        private ClothingSizeDimension chestSizeField;
        
        private string colorMapField;
        
        private string colorNameField;
        
        private string communicationInterfaceField;
        
        private string compatibleDevicesField;
        
        private string controlTypeField;
        
        private string countryOfOriginField;
        
        private string cupSizeField;
        
        private string directionsField;
        
        private LengthDimension displaySizeField;
        
        private string displayTypeField;
        
        private string educationalValueField;
        
        private string fillMaterialTypeField;
        
        private string foldedSizeField;
        
        private ForwardFacingWeight forwardFacingWeightField;
        
        private string frequencyBandsSupportedField;
        
        private FrequencyDimension frequencyResponseField;
        
        private string furnitureFinishField;
        
        private LengthDimension handleHeightField;
        
        private string hardwareVisibilityField;
        
        private string harnessTypeField;
        
        private bool includesAcAdapterField;
        
        private bool includesAcAdapterFieldSpecified;
        
        private bool includesRemoteField;
        
        private bool includesRemoteFieldSpecified;
        
        private string ingredientsField;
        
        private bool isAssemblyRequiredField;
        
        private bool isAssemblyRequiredFieldSpecified;
        
        private bool isDishwasherSafeField;
        
        private bool isDishwasherSafeFieldSpecified;
        
        private bool isPortableField;
        
        private bool isPortableFieldSpecified;
        
        private LengthDimension itemDepthField;
        
        private LengthDimension itemDiameterField;
        
        private VolumeDimension displayVolumeField;
        
        private WeightDimension displayWeightField;
        
        private LengthDimension displayLengthField;
        
        private bool languageFieldSpecified;
        
        private List<string> lifestyleField;
        
        private EnergyConsumptionDimension lithiumBatteryEnergyContentField;
        
        private bool lithiumBatteryPackagingFieldSpecified;
        
        private string manufacturerWarrantyDescriptionField;
        
        private string materialCompositionField;
        
        private string materialTypeField;
        
        private List<string> materialTypeFreeField;
        
        private WeightDimension maximumAnchoringWeightCapacityField;
        
        private LengthDimension maximumHeightRecommendationField;
        
        private OptionalAgeRecommendedDimension maximumManufacturerAgeRecommendedField;
        
        private LengthDimension maximumItemWidthField;
        
        private LengthDimension maximumRangeIndoorsField;
        
        private LengthDimension maximumRangeOpenSpaceField;
        
        private PositiveWeightDimension maximumWeightRecommendationField;
        
        private string mfgWarrantyDescriptionLaborField;
        
        private string mfgWarrantyDescriptionPartsField;
        
        private string mfgWarrantyDescriptionTypeField;
        
        private LengthDimension minimumHeightRecommendationField;
        
        private OptionalAgeRecommendedDimension minimumManufacturerAgeRecommendedField;
        
        private PositiveWeightDimension minimumWeightRecommendationField;
        
        private string numberOfChannelsField;
        
        private string numberOfControlChannelsField;
        
        private string numberOfFrequencyChannelsField;
        
        private string numberOfHeightPositionsField;
        
        private string numberOfLithiumIonCellsField;
        
        private string numberOfLithiumMetalCellsField;
        
        private string numberOfPiecesField;
        
        private string numberOfPlayersField;
        
        private string numberOfPositionsField;
        
        private string operationModeField;
        
        private string orientationField;
        
        private BabyProductsVariationData variationDataField;
        
        private LengthDimension portableDisplaySizeField;
        
        private string powerSourceTypeField;
        
        private string railGaugeField;
        
        private string railTypeField;
        
        private WeightDimension rearFacingMaximumWeightField;
        
        private WeightDimension rearFacingMinimumWeightField;
        
        private List<string> recommendedUsesForProductField;
        
        private string regionOfOriginField;
        
        private string remoteControlTechnologyField;
        
        private string safetyWarningField;
        
        private string scaleNameField;
        
        private LengthDimension seatBackInteriorHeightField;
        
        private LengthDimension seatHeightField;
        
        private LengthDimension seatInteriorWidthField;
        
        private LengthDimension seatLengthField;
        
        private LengthDimension seatWidthField;
        
        private string seatingCapacityField;
        
        private string sellerWarrantyDescriptionField;
        
        private List<string> sensorTechnologyField;
        
        private LengthDimension shoulderHarnessMaximumHeightField;
        
        private LengthDimension shoulderHarnessMinimumHeightField;
        
        private string sizeMapField;
        
        private string sizeNameField;
        
        private List<string> specialFeaturesField;
        
        private List<string> specificUsesForProductField;
        
        private string specificationMetField;
        
        private List<string> styleNameField;
        
        private List<string> subjectCharacterField;
        
        private string suspensionTypeField;
        
        private bool targetGenderFieldSpecified;
        
        private LengthDimension tireDiameterField;
        
        private string tireMaterialField;
        
        private LengthDimension totalTravelField;
        
        private List<string> trayTypeField;
        
        private BabyProductsUnitCount unitCountField;
        
        private string warrantyDescriptionField;
        
        private string wheelTypeField;
        
        private string wirelessCommunicationTechnologyField;
        
        private string unknownSubjectField;
        
        private string engineTypeField;
        
        private string batteryTypeLithiumIonField;
        
        private string batteryTypeLithiumMetalField;
        
        private string lithiumBatteryVoltageField;
        
        private string lithiumBatteryWeightField;
        
        private bool distributionDesignationFieldSpecified;
        
        private string countryStringField;
        
        private string formFactorField;
        
        private string numberOfDrawersField;
        
        private string numberOfLightSourcesField;
        
        private string shadeMaterialTypeField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AlertType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AssemblyInstructions {get; set;}

    public AssemblyTimeDimension AssemblyTime {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AwardsWon {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BaseType {get; set;}

    public LengthDimension BaseWidth {get; set;}

    public Battery Battery {get; set;}

    public BatteryLifeDimension BatteryAverageLife {get; set;}

    public BatteryLifeDimension BatteryAverageLifeStandby {get; set;}

    public TimeDimension BatteryAverageLifeTalkTime {get; set;}

    public BatteryPowerDimension BatteryCapacity {get; set;}

    public BatteryCellTypeValues BatteryCellComposition {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryCellCompositionSpecified {get; set;}

    public TimeDimension BatteryChargeTime {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BatteryDescription {get; set;}

    public BatteryPowerIntegerDimension BatteryPower {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BottleNippleType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BottleType {get; set;}

    public WeightDimension CarrierWeight {get; set;}

    public ClothingSizeDimension ChestSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CommunicationInterface {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibleDevices {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ControlType {get; set;}

    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CupSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Directions {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EducationalValue {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FillMaterialType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FoldedSize {get; set;}

    public ForwardFacingWeight ForwardFacingWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FrequencyBandsSupported {get; set;}

    public FrequencyDimension FrequencyResponse {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FurnitureFinish {get; set;}

    public LengthDimension HandleHeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HardwareVisibility {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HarnessType {get; set;}

    public bool IncludesAcAdapter {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncludesAcAdapterSpecified {get; set;}

    public bool IncludesRemote {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncludesRemoteSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Ingredients {get; set;}

    public bool IsAssemblyRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsAssemblyRequiredSpecified {get; set;}

    public bool IsDishwasherSafe {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsDishwasherSafeSpecified {get; set;}

    public bool IsPortable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPortableSpecified {get; set;}

    public LengthDimension ItemDepth {get; set;}

    public LengthDimension ItemDiameter {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public LengthDimension DisplayLength {get; set;}

    public LanguageStringType Language {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {get; set;}

    public EnergyConsumptionDimension LithiumBatteryEnergyContent {get; set;}

    public BabyProductsLithiumBatteryPackaging LithiumBatteryPackaging {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryPackagingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ManufacturerWarrantyDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MaterialComposition {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MaterialType {get; set;}

    public WeightDimension MaximumAnchoringWeightCapacity {get; set;}

    public LengthDimension MaximumHeightRecommendation {get; set;}

    public OptionalAgeRecommendedDimension MaximumManufacturerAgeRecommended {get; set;}

    public LengthDimension MaximumItemWidth {get; set;}

    public LengthDimension MaximumRangeIndoors {get; set;}

    public LengthDimension MaximumRangeOpenSpace {get; set;}

    public PositiveWeightDimension MaximumWeightRecommendation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfgWarrantyDescriptionLabor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfgWarrantyDescriptionParts {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfgWarrantyDescriptionType {get; set;}

    public LengthDimension MinimumHeightRecommendation {get; set;}

    public OptionalAgeRecommendedDimension MinimumManufacturerAgeRecommended {get; set;}

    public PositiveWeightDimension MinimumWeightRecommendation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfChannels {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfControlChannels {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfFrequencyChannels {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfHeightPositions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumIonCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumMetalCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfPieces {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfPlayers {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfPositions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OperationMode {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Orientation {get; set;}

    public BabyProductsVariationData VariationData {get; set;}

    public LengthDimension PortableDisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PowerSourceType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RailGauge {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RailType {get; set;}

    public WeightDimension RearFacingMaximumWeight {get; set;}

    public WeightDimension RearFacingMinimumWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RegionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RemoteControlTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SafetyWarning {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ScaleName {get; set;}

    public LengthDimension SeatBackInteriorHeight {get; set;}

    public LengthDimension SeatHeight {get; set;}

    public LengthDimension SeatInteriorWidth {get; set;}

    public LengthDimension SeatLength {get; set;}

    public LengthDimension SeatWidth {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string SeatingCapacity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SellerWarrantyDescription {get; set;}

    public LengthDimension ShoulderHarnessMaximumHeight {get; set;}

    public LengthDimension ShoulderHarnessMinimumHeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecificationMet {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SuspensionType {get; set;}

    public TargetGenderType TargetGender {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TargetGenderSpecified {get; set;}

    public LengthDimension TireDiameter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TireMaterial {get; set;}

    public LengthDimension TotalTravel {get; set;}

    public BabyProductsUnitCount UnitCount {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string WarrantyDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string WheelType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string WirelessCommunicationTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string UnknownSubject {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EngineType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BatteryTypeLithiumIon {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BatteryTypeLithiumMetal {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryVoltage {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryWeight {get; set;}

    public DistributionDesignationValues DistributionDesignation {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DistributionDesignationSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CountryString {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FormFactor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfDrawers {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLightSources {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ShadeMaterialType {get; set;}

        
        public BabyProducts() {
            this.unitCountField = new BabyProductsUnitCount();
            this.trayTypeField = new List<string>();
            this.subjectCharacterField = new List<string>();
            this.styleNameField = new List<string>();
            this.specificUsesForProductField = new List<string>();
            this.specialFeaturesField = new List<string>();
            this.sensorTechnologyField = new List<string>();
            this.recommendedUsesForProductField = new List<string>();
            this.variationDataField = new BabyProductsVariationData();
            this.minimumWeightRecommendationField = new PositiveWeightDimension();
            this.minimumManufacturerAgeRecommendedField = new OptionalAgeRecommendedDimension();
            this.maximumWeightRecommendationField = new PositiveWeightDimension();
            this.maximumManufacturerAgeRecommendedField = new OptionalAgeRecommendedDimension();
            this.materialTypeFreeField = new List<string>();
            this.lithiumBatteryEnergyContentField = new EnergyConsumptionDimension();
            this.lifestyleField = new List<string>();
            this.displayVolumeField = new VolumeDimension();
            this.frequencyResponseField = new FrequencyDimension();
            this.chestSizeField = new ClothingSizeDimension();
            this.carSeatWeightGroupEUField = new List<CarSeatWeightGroupEUType>();
            this.careInstructionsField = new List<string>();
            this.batteryPowerField = new BatteryPowerIntegerDimension();
            this.batteryChargeTimeField = new TimeDimension();
            this.batteryCapacityField = new BatteryPowerDimension();
            this.batteryAverageLifeTalkTimeField = new TimeDimension();
            this.batteryAverageLifeStandbyField = new BatteryLifeDimension();
            this.batteryAverageLifeField = new BatteryLifeDimension();
            this.assemblyTimeField = new AssemblyTimeDimension();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CareInstructions", DataType="normalizedString")]
        public List<string> CareInstructions {
            get {
                return this.careInstructionsField;
            }
            set {
                this.careInstructionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CarSeatWeightGroupEU")]
        public List<CarSeatWeightGroupEUType> CarSeatWeightGroupEU {
            get {
                return this.carSeatWeightGroupEUField;
            }
            set {
                this.carSeatWeightGroupEUField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Lifestyle", DataType="normalizedString")]
        public List<string> Lifestyle {
            get {
                return this.lifestyleField;
            }
            set {
                this.lifestyleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaterialTypeFree", DataType="normalizedString")]
        public List<string> MaterialTypeFree {
            get {
                return this.materialTypeFreeField;
            }
            set {
                this.materialTypeFreeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RecommendedUsesForProduct", DataType="normalizedString")]
        public List<string> RecommendedUsesForProduct {
            get {
                return this.recommendedUsesForProductField;
            }
            set {
                this.recommendedUsesForProductField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SensorTechnology", DataType="normalizedString")]
        public List<string> SensorTechnology {
            get {
                return this.sensorTechnologyField;
            }
            set {
                this.sensorTechnologyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecialFeatures", DataType="normalizedString")]
        public List<string> SpecialFeatures {
            get {
                return this.specialFeaturesField;
            }
            set {
                this.specialFeaturesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecificUsesForProduct", DataType="normalizedString")]
        public List<string> SpecificUsesForProduct {
            get {
                return this.specificUsesForProductField;
            }
            set {
                this.specificUsesForProductField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("StyleName", DataType="normalizedString")]
        public List<string> StyleName {
            get {
                return this.styleNameField;
            }
            set {
                this.styleNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SubjectCharacter", DataType="normalizedString")]
        public List<string> SubjectCharacter {
            get {
                return this.subjectCharacterField;
            }
            set {
                this.subjectCharacterField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TrayType", DataType="normalizedString")]
        public List<string> TrayType {
            get {
                return this.trayTypeField;
            }
            set {
                this.trayTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class OptionalAgeRecommendedDimension {
        
        private AgeRecommendedUnitOfMeasure unitOfMeasureField;
        
        private bool unitOfMeasureFieldSpecified;
        
        private string valueField;
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AgeRecommendedUnitOfMeasure unitOfMeasure {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unitOfMeasureSpecified {get; set;}

    [System.Xml.Serialization.XmlTextAttribute(DataType="positiveInteger")]
    public string Value {get; set;}

    }
}
