// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Books {
        
        private BooksProductType productTypeField;
        
    public BooksProductType ProductType {get; set;}

        
        public Books() {
            this.productTypeField = new BooksProductType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BooksMisc {
        
        private string authorField;
        
        private bool dustJacketFieldSpecified;
        
        private string editionField;
        
        private string editorField;
        
        private string illustratorField;
        
        private string introductionField;
        
        private bool isAdultProductField;
        
        private bool isAdultProductFieldSpecified;
        
        private bool isFixedPriceField;
        
        private bool isFixedPriceFieldSpecified;
        
        private bool languageFieldSpecified;
        
        private string narratorField;
        
        private string photographerField;
        
        private string prefaceField;
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        private bool signedByFieldSpecified;
        
        private bool sourcedCountryCodeFieldSpecified;
        
        private string subjectField;
        
        private string translatorField;
        
        private string volumeField;
        
        private string numberOfPagesField;
        
        private string bisacSubjectDescriptionCodeField;
        
        private string collectionNameField;
        
        private string seriesNumberField;
        
        private List<BooksVideoFormatType> formatField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Author {get; set;}

    public BindingTypes Binding {get; set;}

    public DustJacketTypes DustJacket {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DustJacketSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Edition {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Editor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Illustrator {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Introduction {get; set;}

    public bool IsAdultProduct {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsAdultProductSpecified {get; set;}

    public bool IsFixedPrice {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsFixedPriceSpecified {get; set;}

    public LanguageStringType Language {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Narrator {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Photographer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Preface {get; set;}

    public System.DateTime PublicationDate {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PublicationDateSpecified {get; set;}

    public SignedByValues SignedBy {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SignedBySpecified {get; set;}

    public SourceCountryCodeValues SourcedCountryCode {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SourcedCountryCodeSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Subject {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Translator {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Volume {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfPages {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BisacSubjectDescriptionCode {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CollectionName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string SeriesNumber {get; set;}

        
        public BooksMisc() {
            this.formatField = new List<BooksVideoFormatType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Format")]
        public List<BooksVideoFormatType> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
    }
}
