// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Office {
        
        private List<RebateType> rebateField;
        
        private OfficeProductType productTypeField;
        
        private Battery batteryField;
        
        private decimal batteryAverageLifeField;
        
        private bool batteryAverageLifeFieldSpecified;
        
        private decimal batteryAverageLifeStandbyField;
        
        private bool batteryAverageLifeStandbyFieldSpecified;
        
        private decimal batteryChargeTimeField;
        
        private bool batteryChargeTimeFieldSpecified;
        
        private string countryOfOriginField;
        
        private bool isAdultProductField;
        
        private bool isAdultProductFieldSpecified;
        
        private string lithiumBatteryEnergyContentField;
        
        private bool lithiumBatteryPackagingFieldSpecified;
        
        private string lithiumBatteryVoltageField;
        
        private string lithiumBatteryWeightField;
        
        private string mfrWarrantyDescriptionLaborField;
        
        private string mfrWarrantyDescriptionPartsField;
        
        private string manufacturerWarrantyTypeField;
        
        private string numberOfLithiumIonCellsField;
        
        private string numberOfLithiumMetalCellsField;
        
        private string powerSourceField;
        
        private string regionOfOriginField;
        
        private string sellerWarrantyDescriptionField;
        
        private string sizeField;
        
        private string sizeMapField;
        
        private string warningsField;
        
    public OfficeProductType ProductType {get; set;}

    public Battery Battery {get; set;}

    public decimal BatteryAverageLife {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryAverageLifeSpecified {get; set;}

    public decimal BatteryAverageLifeStandby {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryAverageLifeStandbySpecified {get; set;}

    public decimal BatteryChargeTime {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BatteryChargeTimeSpecified {get; set;}

    public string CountryOfOrigin {get; set;}

    public bool IsAdultProduct {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsAdultProductSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryEnergyContent {get; set;}

    public OfficeLithiumBatteryPackaging LithiumBatteryPackaging {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LithiumBatteryPackagingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryVoltage {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string LithiumBatteryWeight {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfrWarrantyDescriptionLabor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MfrWarrantyDescriptionParts {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ManufacturerWarrantyType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumIonCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLithiumMetalCells {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PowerSource {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RegionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SellerWarrantyDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Size {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Warnings {get; set;}

        
        public Office() {
            this.productTypeField = new OfficeProductType();
            this.rebateField = new List<RebateType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Rebate")]
        public List<RebateType> Rebate {
            get {
                return this.rebateField;
            }
            set {
                this.rebateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ArtSupplies {
        
        private ArtSuppliesVariationData variationDataField;
        
        private ArtSuppliesColorSpecification colorSpecificationField;
        
        private string itemPackageQuantityField;
        
        private string numberOfItemsField;
        
        private LengthDimension displayLengthField;
        
        private WeightDimension displayWeightField;
        
        private VolumeDimension displayVolumeField;
        
        private ArtSuppliesUnitCount unitCountField;
        
        private List<string> materialTypeField;
        
        private List<string> paintTypeField;
        
        private decimal recycledContentPercentageField;
        
        private bool recycledContentPercentageFieldSpecified;
        
        private decimal preConsumerRecycledContentField;
        
        private bool preConsumerRecycledContentFieldSpecified;
        
        private decimal postConsumerRecycledContentField;
        
        private bool postConsumerRecycledContentFieldSpecified;
        
        private LengthDimension diameterField;
        
        private LengthDimension maximumExpandableSizeField;
        
        private LengthDimension coreDiameterField;
        
        private List<string> inkColorField;
        
        private string ballpointPenTypeField;
        
        private List<string> tipDescriptionField;
        
        private string pencilLeadHardnessField;
        
        private string pointTypeField;
        
        private LengthDimension lineSizeField;
        
        private string numberOfFastenersField;
        
        private LengthDimension fastenerCapacityField;
        
        private bool bindingFieldSpecified;
        
        private string bindingLocationField;
        
        private string closureTypeField;
        
        private string numberOfHolesField;
        
        private string coverMaterialField;
        
        private string tabCutTypeField;
        
        private string tabPositionField;
        
        private bool isPrePrintedField;
        
        private bool isPrePrintedFieldSpecified;
        
        private string coatingDescriptionField;
        
        private string paperCornerTypeField;
        
        private string paperFinishField;
        
        private LengthDimension paperSizeField;
        
        private string brightnessRatingField;
        
        private string mediaStorageCapacityField;
        
        private string specialFeaturesField;
        
        private List<string> fabricTypeField;
        
        private EnergyConsumptionDimension annualEnergyConsumptionField;
        
        private PowerDimension powerConsumptionField;
        
        private bool eUEnergyLabelEfficiencyClassFieldSpecified;
        
        private string displayTypeField;
        
        private LengthDimension displaySizeField;
        
        private string imageBrightnessField;
        
        private string imageConstrastRatioField;
        
        private string displayResolutionMaximumField;
        
        private AgeRecommendedDimension mfgMaximumField;
        
        private string lockTypeField;
        
        private string compatibilityOptionsField;
        
        private string calenderTypeField;
        
        private bool isWhiteGloveRequiredField;
        
        private bool isWhiteGloveRequiredFieldSpecified;
        
        private string modelYearRangeField;
        
        private string numberOfLinesField;
        
        private DensityDimension itemDensityField;
        
        private string itemShapeField;
        
        private string subjectCharacterField;
        
        private string itemTypeNameField;
        
        private string occasionField;
        
        private string occasionTypeField;
        
    public ArtSuppliesVariationData VariationData {get; set;}

    public ArtSuppliesColorSpecification ColorSpecification {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfItems {get; set;}

    public LengthDimension DisplayLength {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public ArtSuppliesUnitCount UnitCount {get; set;}

    public decimal RecycledContentPercentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecycledContentPercentageSpecified {get; set;}

    public decimal PreConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreConsumerRecycledContentSpecified {get; set;}

    public decimal PostConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostConsumerRecycledContentSpecified {get; set;}

    public LengthDimension Diameter {get; set;}

    public LengthDimension MaximumExpandableSize {get; set;}

    public LengthDimension CoreDiameter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BallpointPenType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PencilLeadHardness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PointType {get; set;}

    public LengthDimension LineSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfFasteners {get; set;}

    public LengthDimension FastenerCapacity {get; set;}

    public BindingType Binding {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BindingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BindingLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ClosureType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfHoles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoverMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabCutType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabPosition {get; set;}

    public bool IsPrePrinted {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPrePrintedSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoatingDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperCornerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperFinish {get; set;}

    public LengthDimension PaperSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BrightnessRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MediaStorageCapacity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    public EnergyConsumptionDimension AnnualEnergyConsumption {get; set;}

    public PowerDimension PowerConsumption {get; set;}

    public EnergyLabelEfficiencyClass EUEnergyLabelEfficiencyClass {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EUEnergyLabelEfficiencyClassSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageBrightness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageConstrastRatio {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayResolutionMaximum {get; set;}

    public AgeRecommendedDimension MfgMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LockType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibilityOptions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CalenderType {get; set;}

    public bool IsWhiteGloveRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsWhiteGloveRequiredSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ModelYearRange {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLines {get; set;}

    public DensityDimension ItemDensity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemShape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubjectCharacter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Occasion {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OccasionType {get; set;}

        
        public ArtSupplies() {
            this.itemDensityField = new DensityDimension();
            this.powerConsumptionField = new PowerDimension();
            this.annualEnergyConsumptionField = new EnergyConsumptionDimension();
            this.fabricTypeField = new List<string>();
            this.tipDescriptionField = new List<string>();
            this.inkColorField = new List<string>();
            this.paintTypeField = new List<string>();
            this.materialTypeField = new List<string>();
            this.unitCountField = new ArtSuppliesUnitCount();
            this.displayVolumeField = new VolumeDimension();
            this.colorSpecificationField = new ArtSuppliesColorSpecification();
            this.variationDataField = new ArtSuppliesVariationData();
            this.itemPackageQuantityField = "1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string ItemPackageQuantity {
            get {
                return this.itemPackageQuantityField;
            }
            set {
                this.itemPackageQuantityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaterialType", DataType="normalizedString")]
        public List<string> MaterialType {
            get {
                return this.materialTypeField;
            }
            set {
                this.materialTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PaintType", DataType="normalizedString")]
        public List<string> PaintType {
            get {
                return this.paintTypeField;
            }
            set {
                this.paintTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("InkColor", DataType="normalizedString")]
        public List<string> InkColor {
            get {
                return this.inkColorField;
            }
            set {
                this.inkColorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TipDescription", DataType="normalizedString")]
        public List<string> TipDescription {
            get {
                return this.tipDescriptionField;
            }
            set {
                this.tipDescriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FabricType", DataType="normalizedString")]
        public List<string> FabricType {
            get {
                return this.fabricTypeField;
            }
            set {
                this.fabricTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BarCode {
        
        private BarCodeVariationData variationDataField;
        
        private bool includesRechargableBatteryField;
        
        private bool includesRechargableBatteryFieldSpecified;
        
        private string noiseAttenuationField;
        
        private string hardwarePlatformField;
        
        private string inputDeviceInterfaceField;
        
        private string connectivityTechnologyField;
        
        private string specialFeaturesField;
        
        private string powerDeviceField;
        
        private string scanElementTypeField;
        
        private string scanRateField;
        
        private string colorField;
        
    public BarCodeVariationData VariationData {get; set;}

    public bool IncludesRechargableBattery {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncludesRechargableBatterySpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string NoiseAttenuation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string HardwarePlatform {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string InputDeviceInterface {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ConnectivityTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PowerDevice {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ScanElementType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ScanRate {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public BarCode() {
            this.variationDataField = new BarCodeVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Calculator {
        
        private CalculatorVariationData variationDataField;
        
        private bool includesRechargableBatteryField;
        
        private bool includesRechargableBatteryFieldSpecified;
        
        private string colorField;
        
    public CalculatorVariationData VariationData {get; set;}

    public bool IncludesRechargableBattery {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncludesRechargableBatterySpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public Calculator() {
            this.variationDataField = new CalculatorVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class EducationalSupplies {
        
        private EducationalSuppliesVariationData variationDataField;
        
        private EducationalSuppliesColorSpecification colorSpecificationField;
        
        private string itemPackageQuantityField;
        
        private string numberOfItemsField;
        
        private LengthDimension displayLengthField;
        
        private WeightDimension displayWeightField;
        
        private VolumeDimension displayVolumeField;
        
        private EducationalSuppliesUnitCount unitCountField;
        
        private decimal recycledContentPercentageField;
        
        private bool recycledContentPercentageFieldSpecified;
        
        private decimal preConsumerRecycledContentField;
        
        private bool preConsumerRecycledContentFieldSpecified;
        
        private decimal postConsumerRecycledContentField;
        
        private bool postConsumerRecycledContentFieldSpecified;
        
        private LengthDimension diameterField;
        
        private LengthDimension maximumExpandableSizeField;
        
        private LengthDimension coreDiameterField;
        
        private List<string> inkColorField;
        
        private string ballpointPenTypeField;
        
        private List<string> tipDescriptionField;
        
        private string pencilLeadHardnessField;
        
        private string pointTypeField;
        
        private LengthDimension lineSizeField;
        
        private string numberOfFastenersField;
        
        private LengthDimension fastenerCapacityField;
        
        private BindingType bindingField;
        
        private bool bindingFieldSpecified;
        
        private string bindingLocationField;
        
        private string closureTypeField;
        
        private string numberOfHolesField;
        
        private string coverMaterialField;
        
        private string tabCutTypeField;
        
        private string tabPositionField;
        
        private bool isPrePrintedField;
        
        private bool isPrePrintedFieldSpecified;
        
        private string coatingDescriptionField;
        
        private string paperCornerTypeField;
        
        private string paperFinishField;
        
        private LengthDimension paperSizeField;
        
        private string brightnessRatingField;
        
        private string mediaStorageCapacityField;
        
        private string specialFeaturesField;
        
        private string rulingTypeField;
        
        private EnergyConsumptionDimension annualEnergyConsumptionField;
        
        private PowerDimension powerConsumptionField;
        
        private EnergyLabelEfficiencyClass eUEnergyLabelEfficiencyClassField;
        
        private bool eUEnergyLabelEfficiencyClassFieldSpecified;
        
        private string displayTypeField;
        
        private LengthDimension displaySizeField;
        
        private string imageBrightnessField;
        
        private string imageConstrastRatioField;
        
        private string displayResolutionMaximumField;
        
        private string paintTypeField;
        
        private AgeRecommendedDimension mfgMinimumField;
        
        private AgeRecommendedDimension mfgMaximumField;
        
        private string lockTypeField;
        
        private string compatibilityOptionsField;
        
        private string calenderTypeField;
        
        private bool isWhiteGloveRequiredField;
        
        private bool isWhiteGloveRequiredFieldSpecified;
        
        private string modelYearRangeField;
        
        private string numberOfLinesField;
        
        private DensityDimension itemDensityField;
        
        private string itemShapeField;
        
        private string subjectCharacterField;
        
        private string itemTypeNameField;
        
        private string occasionField;
        
    public EducationalSuppliesVariationData VariationData {get; set;}

    public EducationalSuppliesColorSpecification ColorSpecification {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfItems {get; set;}

    public LengthDimension DisplayLength {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public EducationalSuppliesUnitCount UnitCount {get; set;}

    public decimal RecycledContentPercentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecycledContentPercentageSpecified {get; set;}

    public decimal PreConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreConsumerRecycledContentSpecified {get; set;}

    public decimal PostConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostConsumerRecycledContentSpecified {get; set;}

    public LengthDimension Diameter {get; set;}

    public LengthDimension MaximumExpandableSize {get; set;}

    public LengthDimension CoreDiameter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BallpointPenType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PencilLeadHardness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PointType {get; set;}

    public LengthDimension LineSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfFasteners {get; set;}

    public LengthDimension FastenerCapacity {get; set;}

    public BindingType Binding {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BindingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BindingLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ClosureType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfHoles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoverMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabCutType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabPosition {get; set;}

    public bool IsPrePrinted {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPrePrintedSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoatingDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperCornerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperFinish {get; set;}

    public LengthDimension PaperSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BrightnessRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MediaStorageCapacity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RulingType {get; set;}

    public EnergyConsumptionDimension AnnualEnergyConsumption {get; set;}

    public PowerDimension PowerConsumption {get; set;}

    public EnergyLabelEfficiencyClass EUEnergyLabelEfficiencyClass {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EUEnergyLabelEfficiencyClassSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageBrightness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageConstrastRatio {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayResolutionMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaintType {get; set;}

    public AgeRecommendedDimension MfgMinimum {get; set;}

    public AgeRecommendedDimension MfgMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LockType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibilityOptions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CalenderType {get; set;}

    public bool IsWhiteGloveRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsWhiteGloveRequiredSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ModelYearRange {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLines {get; set;}

    public DensityDimension ItemDensity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemShape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubjectCharacter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Occasion {get; set;}

        
        public EducationalSupplies() {
            this.tipDescriptionField = new List<string>();
            this.inkColorField = new List<string>();
            this.unitCountField = new EducationalSuppliesUnitCount();
            this.colorSpecificationField = new EducationalSuppliesColorSpecification();
            this.variationDataField = new EducationalSuppliesVariationData();
            this.itemPackageQuantityField = "1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string ItemPackageQuantity {
            get {
                return this.itemPackageQuantityField;
            }
            set {
                this.itemPackageQuantityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("InkColor", DataType="normalizedString")]
        public List<string> InkColor {
            get {
                return this.inkColorField;
            }
            set {
                this.inkColorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TipDescription", DataType="normalizedString")]
        public List<string> TipDescription {
            get {
                return this.tipDescriptionField;
            }
            set {
                this.tipDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class InkToner {
        
        private InkTonerVariationData variationDataField;
        
        private string connectivityTechnologyField;
        
        private string inkColorField;
        
        private string maxPrintspeedBlackWhiteField;
        
        private string maxPrintspeedColorField;
        
        private string printerOutputField;
        
        private string printerTechnologyField;
        
        private string compatibleDevicesField;
        
        private string colorField;
        
        private EnergyConsumptionDimension annualEnergyConsumptionField;
        
        private PowerDimension powerConsumptionField;
        
        private EnergyLabelEfficiencyClass eUEnergyLabelEfficiencyClassField;
        
        private bool eUEnergyLabelEfficiencyClassFieldSpecified;
        
        private string displayTypeField;
        
        private LengthDimension displaySizeField;
        
        private string imageBrightnessField;
        
        private string imageConstrastRatioField;
        
        private string displayResolutionMaximumField;
        
        private string itemShapeField;
        
        private string paintTypeField;
        
        private AgeRecommendedDimension mfgMinimumField;
        
        private AgeRecommendedDimension mfgMaximumField;
        
        private string lockTypeField;
        
        private DensityDimension itemDensityField;
        
        private string compatibilityOptionsField;
        
        private string itemTypeNameField;
        
        private string occasionField;
        
    public InkTonerVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ConnectivityTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string InkColor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxPrintspeedBlackWhite {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxPrintspeedColor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PrinterOutput {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PrinterTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibleDevices {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

    public EnergyConsumptionDimension AnnualEnergyConsumption {get; set;}

    public PowerDimension PowerConsumption {get; set;}

    public EnergyLabelEfficiencyClass EUEnergyLabelEfficiencyClass {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EUEnergyLabelEfficiencyClassSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageBrightness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageConstrastRatio {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayResolutionMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemShape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaintType {get; set;}

    public AgeRecommendedDimension MfgMinimum {get; set;}

    public AgeRecommendedDimension MfgMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LockType {get; set;}

    public DensityDimension ItemDensity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibilityOptions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Occasion {get; set;}

        
        public InkToner() {
            this.variationDataField = new InkTonerVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MultifunctionDevice {
        
        private MultifunctionDeviceVariationData variationDataField;
        
        private string connectivityTechnologyField;
        
        private string includedFeaturesField;
        
        private string productTypeSubcategoryField;
        
        private string colorField;
        
    public MultifunctionDeviceVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ConnectivityTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IncludedFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ProductTypeSubcategory {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public MultifunctionDevice() {
            this.variationDataField = new MultifunctionDeviceVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OfficeElectronics {
        
        private OfficeElectronicsVariationData variationDataField;
        
        private string resolutionBaseField;
        
        private string displayTypeField;
        
        private string displayTechnologyField;
        
        private string colorField;
        
    public OfficeElectronicsVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ResolutionBase {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public OfficeElectronics() {
            this.variationDataField = new OfficeElectronicsVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OfficePhone {
        
        private OfficePhoneVariationData variationDataField;
        
        private string colorField;
        
        private bool includesRechargableBatteryField;
        
        private bool includesRechargableBatteryFieldSpecified;
        
        private string noiseAttenuationField;
        
        private string specialFeaturesField;
        
        private bool callerIdentificationField;
        
        private bool callerIdentificationFieldSpecified;
        
        private string radioBandsSupportedField;
        
    public OfficePhoneVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

    public bool IncludesRechargableBattery {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncludesRechargableBatterySpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string NoiseAttenuation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    public bool CallerIdentification {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CallerIdentificationSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RadioBandsSupported {get; set;}

        
        public OfficePhone() {
            this.variationDataField = new OfficePhoneVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OfficePrinter {
        
        private OfficePrinterVariationData variationDataField;
        
        private string connectivityTechnologyField;
        
        private string maxPrintspeedBlackWhiteField;
        
        private string maxPrintspeedColorField;
        
        private string printerOutputField;
        
        private string printerTechnologyField;
        
        private string colorField;
        
    public OfficePrinterVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ConnectivityTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxPrintspeedBlackWhite {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string MaxPrintspeedColor {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PrinterOutput {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PrinterTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public OfficePrinter() {
            this.variationDataField = new OfficePrinterVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OfficeProducts {
        
        private OfficeProductsVariationData variationDataField;
        
        private OfficeProductsColorSpecification colorSpecificationField;
        
        private string itemPackageQuantityField;
        
        private string numberOfItemsField;
        
        private LengthDimension displayLengthField;
        
        private WeightDimension displayWeightField;
        
        private VolumeDimension displayVolumeField;
        
        private OfficeProductsUnitCount unitCountField;
        
        private List<string> materialTypeField;
        
        private decimal recycledContentPercentageField;
        
        private bool recycledContentPercentageFieldSpecified;
        
        private decimal preConsumerRecycledContentField;
        
        private bool preConsumerRecycledContentFieldSpecified;
        
        private decimal postConsumerRecycledContentField;
        
        private bool postConsumerRecycledContentFieldSpecified;
        
        private LengthDimension diameterField;
        
        private LengthDimension maximumExpandableSizeField;
        
        private LengthDimension coreDiameterField;
        
        private List<string> inkColorField;
        
        private string ballpointPenTypeField;
        
        private List<string> tipDescriptionField;
        
        private string pencilLeadHardnessField;
        
        private string pointTypeField;
        
        private LengthDimension lineSizeField;
        
        private string numberOfFastenersField;
        
        private LengthDimension fastenerCapacityField;
        
        private BindingType bindingField;
        
        private bool bindingFieldSpecified;
        
        private string bindingLocationField;
        
        private string closureTypeField;
        
        private string numberOfHolesField;
        
        private string coverMaterialField;
        
        private string tabCutTypeField;
        
        private string tabPositionField;
        
        private bool isPrePrintedField;
        
        private bool isPrePrintedFieldSpecified;
        
        private string coatingDescriptionField;
        
        private string paperCornerTypeField;
        
        private string paperFinishField;
        
        private LengthDimension paperSizeField;
        
        private string brightnessRatingField;
        
        private string mediaStorageCapacityField;
        
        private string specialFeaturesField;
        
        private string rulingTypeField;
        
        private EnergyConsumptionDimension annualEnergyConsumptionField;
        
        private PowerDimension powerConsumptionField;
        
        private EnergyLabelEfficiencyClass eUEnergyLabelEfficiencyClassField;
        
        private bool eUEnergyLabelEfficiencyClassFieldSpecified;
        
        private string displayTypeField;
        
        private LengthDimension displaySizeField;
        
        private string imageBrightnessField;
        
        private string imageConstrastRatioField;
        
        private string displayResolutionMaximumField;
        
        private string paintTypeField;
        
        private AgeRecommendedDimension mfgMinimumField;
        
        private AgeRecommendedDimension mfgMaximumField;
        
        private string lockTypeField;
        
        private string compatibilityOptionsField;
        
        private string calenderTypeField;
        
        private CapacityUnit capacityField;
        
        private bool isWhiteGloveRequiredField;
        
        private bool isWhiteGloveRequiredFieldSpecified;
        
        private string modelYearRangeField;
        
        private string numberOfLinesField;
        
        private string itemTypeNameField;
        
        private DensityDimension itemDensityField;
        
        private string occasionField;
        
    public OfficeProductsVariationData VariationData {get; set;}

    public OfficeProductsColorSpecification ColorSpecification {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfItems {get; set;}

    public LengthDimension DisplayLength {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public OfficeProductsUnitCount UnitCount {get; set;}

    public decimal RecycledContentPercentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecycledContentPercentageSpecified {get; set;}

    public decimal PreConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreConsumerRecycledContentSpecified {get; set;}

    public decimal PostConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostConsumerRecycledContentSpecified {get; set;}

    public LengthDimension Diameter {get; set;}

    public LengthDimension MaximumExpandableSize {get; set;}

    public LengthDimension CoreDiameter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BallpointPenType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PencilLeadHardness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PointType {get; set;}

    public LengthDimension LineSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfFasteners {get; set;}

    public LengthDimension FastenerCapacity {get; set;}

    public BindingType Binding {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BindingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BindingLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ClosureType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfHoles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoverMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabCutType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabPosition {get; set;}

    public bool IsPrePrinted {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPrePrintedSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoatingDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperCornerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperFinish {get; set;}

    public LengthDimension PaperSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BrightnessRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MediaStorageCapacity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RulingType {get; set;}

    public EnergyConsumptionDimension AnnualEnergyConsumption {get; set;}

    public PowerDimension PowerConsumption {get; set;}

    public EnergyLabelEfficiencyClass EUEnergyLabelEfficiencyClass {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EUEnergyLabelEfficiencyClassSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageBrightness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageConstrastRatio {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayResolutionMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaintType {get; set;}

    public AgeRecommendedDimension MfgMinimum {get; set;}

    public AgeRecommendedDimension MfgMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LockType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibilityOptions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CalenderType {get; set;}

    public CapacityUnit Capacity {get; set;}

    public bool IsWhiteGloveRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsWhiteGloveRequiredSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ModelYearRange {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLines {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

    public DensityDimension ItemDensity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Occasion {get; set;}

        
        public OfficeProducts() {
            this.capacityField = new CapacityUnit();
            this.tipDescriptionField = new List<string>();
            this.inkColorField = new List<string>();
            this.materialTypeField = new List<string>();
            this.unitCountField = new OfficeProductsUnitCount();
            this.colorSpecificationField = new OfficeProductsColorSpecification();
            this.variationDataField = new OfficeProductsVariationData();
            this.itemPackageQuantityField = "1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string ItemPackageQuantity {
            get {
                return this.itemPackageQuantityField;
            }
            set {
                this.itemPackageQuantityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaterialType", DataType="normalizedString")]
        public List<string> MaterialType {
            get {
                return this.materialTypeField;
            }
            set {
                this.materialTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("InkColor", DataType="normalizedString")]
        public List<string> InkColor {
            get {
                return this.inkColorField;
            }
            set {
                this.inkColorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TipDescription", DataType="normalizedString")]
        public List<string> TipDescription {
            get {
                return this.tipDescriptionField;
            }
            set {
                this.tipDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OfficeScanner {
        
        private OfficeScannerVariationData variationDataField;
        
        private string connectivityTechnologyField;
        
        private string specialFeaturesField;
        
        private string productTypeSubcategoryField;
        
        private string operatingSystemField;
        
        private string colorField;
        
    public OfficeScannerVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ConnectivityTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ProductTypeSubcategory {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OperatingSystem {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public OfficeScanner() {
            this.variationDataField = new OfficeScannerVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PaperProducts {
        
        private PaperProductsVariationData variationDataField;
        
        private PaperProductsColorSpecification colorSpecificationField;
        
        private string itemPackageQuantityField;
        
        private string numberOfItemsField;
        
        private LengthDimension displayLengthField;
        
        private WeightDimension displayWeightField;
        
        private VolumeDimension displayVolumeField;
        
        private PaperProductsUnitCount unitCountField;
        
        private decimal recycledContentPercentageField;
        
        private bool recycledContentPercentageFieldSpecified;
        
        private decimal preConsumerRecycledContentField;
        
        private bool preConsumerRecycledContentFieldSpecified;
        
        private decimal postConsumerRecycledContentField;
        
        private bool postConsumerRecycledContentFieldSpecified;
        
        private LengthDimension diameterField;
        
        private LengthDimension maximumExpandableSizeField;
        
        private LengthDimension coreDiameterField;
        
        private string numberOfFastenersField;
        
        private LengthDimension fastenerCapacityField;
        
        private BindingType bindingField;
        
        private bool bindingFieldSpecified;
        
        private string bindingLocationField;
        
        private string closureTypeField;
        
        private string numberOfHolesField;
        
        private string coverMaterialField;
        
        private string tabCutTypeField;
        
        private string tabPositionField;
        
        private bool isPrePrintedField;
        
        private bool isPrePrintedFieldSpecified;
        
        private string coatingDescriptionField;
        
        private string paperCornerTypeField;
        
        private string paperFinishField;
        
        private LengthDimension paperSizeField;
        
        private string brightnessRatingField;
        
        private string specialFeaturesField;
        
        private string rulingTypeField;
        
        private EnergyConsumptionDimension annualEnergyConsumptionField;
        
        private PowerDimension powerConsumptionField;
        
        private EnergyLabelEfficiencyClass eUEnergyLabelEfficiencyClassField;
        
        private bool eUEnergyLabelEfficiencyClassFieldSpecified;
        
        private string displayTypeField;
        
        private LengthDimension displaySizeField;
        
        private string imageBrightnessField;
        
        private string imageConstrastRatioField;
        
        private string displayResolutionMaximumField;
        
        private string paintTypeField;
        
        private AgeRecommendedDimension mfgMinimumField;
        
        private AgeRecommendedDimension mfgMaximumField;
        
        private string lockTypeField;
        
        private string compatibilityOptionsField;
        
        private string calenderTypeField;
        
        private bool isWhiteGloveRequiredField;
        
        private bool isWhiteGloveRequiredFieldSpecified;
        
        private string modelYearRangeField;
        
        private string numberOfLinesField;
        
        private DensityDimension itemDensityField;
        
        private string occasionTypeField;
        
        private string occasionField;
        
        private string itemTypeNameField;
        
    public PaperProductsVariationData VariationData {get; set;}

    public PaperProductsColorSpecification ColorSpecification {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfItems {get; set;}

    public LengthDimension DisplayLength {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public PaperProductsUnitCount UnitCount {get; set;}

    public decimal RecycledContentPercentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecycledContentPercentageSpecified {get; set;}

    public decimal PreConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreConsumerRecycledContentSpecified {get; set;}

    public decimal PostConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostConsumerRecycledContentSpecified {get; set;}

    public LengthDimension Diameter {get; set;}

    public LengthDimension MaximumExpandableSize {get; set;}

    public LengthDimension CoreDiameter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfFasteners {get; set;}

    public LengthDimension FastenerCapacity {get; set;}

    public BindingType Binding {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BindingSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BindingLocation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ClosureType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfHoles {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoverMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabCutType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TabPosition {get; set;}

    public bool IsPrePrinted {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPrePrintedSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CoatingDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperCornerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaperFinish {get; set;}

    public LengthDimension PaperSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BrightnessRating {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RulingType {get; set;}

    public EnergyConsumptionDimension AnnualEnergyConsumption {get; set;}

    public PowerDimension PowerConsumption {get; set;}

    public EnergyLabelEfficiencyClass EUEnergyLabelEfficiencyClass {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EUEnergyLabelEfficiencyClassSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageBrightness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageConstrastRatio {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayResolutionMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaintType {get; set;}

    public AgeRecommendedDimension MfgMinimum {get; set;}

    public AgeRecommendedDimension MfgMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LockType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibilityOptions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CalenderType {get; set;}

    public bool IsWhiteGloveRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsWhiteGloveRequiredSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ModelYearRange {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfLines {get; set;}

    public DensityDimension ItemDensity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OccasionType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Occasion {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

        
        public PaperProducts() {
            this.unitCountField = new PaperProductsUnitCount();
            this.colorSpecificationField = new PaperProductsColorSpecification();
            this.variationDataField = new PaperProductsVariationData();
            this.itemPackageQuantityField = "1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string ItemPackageQuantity {
            get {
                return this.itemPackageQuantityField;
            }
            set {
                this.itemPackageQuantityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VoiceRecorder {
        
        private VoiceRecorderVariationData variationDataField;
        
        private string colorField;
        
    public VoiceRecorderVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Color {get; set;}

        
        public VoiceRecorder() {
            this.variationDataField = new VoiceRecorderVariationData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WritingInstruments {
        
        private WritingInstrumentsVariationData variationDataField;
        
        private WritingInstrumentsColorSpecification colorSpecificationField;
        
        private string itemPackageQuantityField;
        
        private string numberOfItemsField;
        
        private LengthDimension displayLengthField;
        
        private WeightDimension displayWeightField;
        
        private VolumeDimension displayVolumeField;
        
        private WritingInstrumentsUnitCount unitCountField;
        
        private List<string> materialTypeField;
        
        private decimal recycledContentPercentageField;
        
        private bool recycledContentPercentageFieldSpecified;
        
        private decimal preConsumerRecycledContentField;
        
        private bool preConsumerRecycledContentFieldSpecified;
        
        private decimal postConsumerRecycledContentField;
        
        private bool postConsumerRecycledContentFieldSpecified;
        
        private LengthDimension diameterField;
        
        private List<string> inkColorField;
        
        private string ballpointPenTypeField;
        
        private List<string> tipDescriptionField;
        
        private string pencilLeadHardnessField;
        
        private string pointTypeField;
        
        private LengthDimension lineSizeField;
        
        private string specialFeaturesField;
        
        private EnergyConsumptionDimension annualEnergyConsumptionField;
        
        private PowerDimension powerConsumptionField;
        
        private EnergyLabelEfficiencyClass eUEnergyLabelEfficiencyClassField;
        
        private bool eUEnergyLabelEfficiencyClassFieldSpecified;
        
        private string displayTypeField;
        
        private LengthDimension displaySizeField;
        
        private string imageBrightnessField;
        
        private string imageConstrastRatioField;
        
        private string displayResolutionMaximumField;
        
        private string paintTypeField;
        
        private AgeRecommendedDimension mfgMinimumField;
        
        private AgeRecommendedDimension mfgMaximumField;
        
        private string lockTypeField;
        
        private string compatibilityOptionsField;
        
        private string calenderTypeField;
        
        private bool isWhiteGloveRequiredField;
        
        private bool isWhiteGloveRequiredFieldSpecified;
        
        private string modelYearRangeField;
        
        private DensityDimension itemDensityField;
        
        private string itemShapeField;
        
        private string subjectCharacterField;
        
        private string itemTypeNameField;
        
        private string occasionField;
        
    public WritingInstrumentsVariationData VariationData {get; set;}

    public WritingInstrumentsColorSpecification ColorSpecification {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfItems {get; set;}

    public LengthDimension DisplayLength {get; set;}

    public WeightDimension DisplayWeight {get; set;}

    public VolumeDimension DisplayVolume {get; set;}

    public WritingInstrumentsUnitCount UnitCount {get; set;}

    public decimal RecycledContentPercentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecycledContentPercentageSpecified {get; set;}

    public decimal PreConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreConsumerRecycledContentSpecified {get; set;}

    public decimal PostConsumerRecycledContent {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PostConsumerRecycledContentSpecified {get; set;}

    public LengthDimension Diameter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BallpointPenType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PencilLeadHardness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PointType {get; set;}

    public LengthDimension LineSize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialFeatures {get; set;}

    public EnergyConsumptionDimension AnnualEnergyConsumption {get; set;}

    public PowerDimension PowerConsumption {get; set;}

    public EnergyLabelEfficiencyClass EUEnergyLabelEfficiencyClass {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EUEnergyLabelEfficiencyClassSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayType {get; set;}

    public LengthDimension DisplaySize {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageBrightness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ImageConstrastRatio {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DisplayResolutionMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PaintType {get; set;}

    public AgeRecommendedDimension MfgMinimum {get; set;}

    public AgeRecommendedDimension MfgMaximum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LockType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CompatibilityOptions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CalenderType {get; set;}

    public bool IsWhiteGloveRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsWhiteGloveRequiredSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ModelYearRange {get; set;}

    public DensityDimension ItemDensity {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemShape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubjectCharacter {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Occasion {get; set;}

        
        public WritingInstruments() {
            this.tipDescriptionField = new List<string>();
            this.inkColorField = new List<string>();
            this.materialTypeField = new List<string>();
            this.unitCountField = new WritingInstrumentsUnitCount();
            this.colorSpecificationField = new WritingInstrumentsColorSpecification();
            this.variationDataField = new WritingInstrumentsVariationData();
            this.itemPackageQuantityField = "1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string ItemPackageQuantity {
            get {
                return this.itemPackageQuantityField;
            }
            set {
                this.itemPackageQuantityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaterialType", DataType="normalizedString")]
        public List<string> MaterialType {
            get {
                return this.materialTypeField;
            }
            set {
                this.materialTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("InkColor", DataType="normalizedString")]
        public List<string> InkColor {
            get {
                return this.inkColorField;
            }
            set {
                this.inkColorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TipDescription", DataType="normalizedString")]
        public List<string> TipDescription {
            get {
                return this.tipDescriptionField;
            }
            set {
                this.tipDescriptionField = value;
            }
        }
    }
}
