// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OrderNotificationReport {
        
        private bool languageFieldSpecified;
        
        private string orderStatusField;
        
        private string orderChannelField;
        
        private string amazonOrderIDField;
        
        private string marketplaceNameField;
        
        private string amazonCustomerIDField;
        
        private string amazonSessionIDField;
        
        private System.DateTime orderDateField;
        
        private List<OrderNotificationReportCustomerOrderInfo> customerOrderInfoField;
        
        private OrderNotificationReportBillingData billingDataField;
        
        private List<OrderNotificationReportPromotion> promotionField;
        
        private OrderNotificationReportFulfillmentData fulfillmentDataField;
        
        private List<OrderNotificationReportItem> itemField;
        
    public LanguageType Language {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OrderStatus {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OrderChannel {get; set;}

    public string AmazonOrderID {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MarketplaceName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AmazonCustomerID {get; set;}

    public string AmazonSessionID {get; set;}

    public System.DateTime OrderDate {get; set;}

    public OrderNotificationReportBillingData BillingData {get; set;}

    public OrderNotificationReportFulfillmentData FulfillmentData {get; set;}

        
        public OrderNotificationReport() {
            this.itemField = new List<OrderNotificationReportItem>();
            this.fulfillmentDataField = new OrderNotificationReportFulfillmentData();
            this.promotionField = new List<OrderNotificationReportPromotion>();
            this.billingDataField = new OrderNotificationReportBillingData();
            this.customerOrderInfoField = new List<OrderNotificationReportCustomerOrderInfo>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomerOrderInfo")]
        public List<OrderNotificationReportCustomerOrderInfo> CustomerOrderInfo {
            get {
                return this.customerOrderInfoField;
            }
            set {
                this.customerOrderInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Promotion")]
        public List<OrderNotificationReportPromotion> Promotion {
            get {
                return this.promotionField;
            }
            set {
                this.promotionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public List<OrderNotificationReportItem> Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
