// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ThreeDPrinting {
        
        private bool productTypeFieldSpecified;
        
        private ThreeDPrintingVariationData variationDataField;
        
        private LengthDimension displayDiameterField;
        
        private LengthDimension displayLengthField;
        
        private string styleKeywordsField;
        
        private string originDescriptionField;
        
        private List<string> certificateTypeField;
        
        private List<string> certificateNumberField;
        
        private string designFileUrlField;
        
        private bool isAdultProductField;
        
        private bool isAdultProductFieldSpecified;
        
        private string volumeBaseField;
        
        private string itemDepthField;
        
        private List<string> departmentNameField;
        
        private string themeField;
        
        private List<string> genreField;
        
        private MinimumAgeRecommendedDimension mfgMinimumField;
        
        private string videoUrlField;
        
        private List<string> styleNameField;
        
        private List<string> specialFeaturesField;
        
        private List<string> specialSizeTypeField;
        
        private string beltStyleField;
        
        private string itemShapeField;
        
        private string frameMaterialTypeField;
        
        private string lensMaterialTypeField;
        
        private List<string> compatiblePhoneModelsField;
        
        private List<string> compatibleDevicesField;
        
        private List<string> includedComponentsField;
        
        private string numberOfPiecesField;
        
        private string installationTypeField;
        
        private bool isAssemblyRequiredField;
        
        private bool isAssemblyRequiredFieldSpecified;
        
        private string skillLevelField;
        
        private List<string> materialTypeField;
        
        private string metalTypeField;
        
        private string colorNameField;
        
        private string colorMapField;
        
        private string sizeNameField;
        
        private bool isCustomizableField;
        
        private bool isCustomizableFieldSpecified;
        
        private string additionalProductInformationField;
        
        private string recommendedUserBuildField;
        
        private string printingTechnologyField;
        
        private string itemHardnessField;
        
        private string itemFirmnessDescriptionField;
        
        private bool isVeryHighValueField;
        
        private bool isVeryHighValueFieldSpecified;
        
        private List<string> supportedDevicesField;
        
        private string itemTypeNameField;
        
        private string preferredManufacturerField;
        
        private string additionalSizeInformationField;
        
        private List<string> finishTypeField;
        
    public ThreeDPrintingProductType ProductType {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProductTypeSpecified {get; set;}

    public ThreeDPrintingVariationData VariationData {get; set;}

    public LengthDimension DisplayDiameter {get; set;}

    public LengthDimension DisplayLength {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StyleKeywords {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OriginDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string DesignFileUrl {get; set;}

    public bool IsAdultProduct {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsAdultProductSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string VolumeBase {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemDepth {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Theme {get; set;}

    public MinimumAgeRecommendedDimension MfgMinimum {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string VideoUrl {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BeltStyle {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemShape {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FrameMaterialType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LensMaterialType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string NumberOfPieces {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string InstallationType {get; set;}

    public bool IsAssemblyRequired {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsAssemblyRequiredSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SkillLevel {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string MetalType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SizeName {get; set;}

    public bool IsCustomizable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsCustomizableSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AdditionalProductInformation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RecommendedUserBuild {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PrintingTechnology {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemHardness {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemFirmnessDescription {get; set;}

    public bool IsVeryHighValue {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsVeryHighValueSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ItemTypeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PreferredManufacturer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AdditionalSizeInformation {get; set;}

        
        public ThreeDPrinting() {
            this.finishTypeField = new List<string>();
            this.supportedDevicesField = new List<string>();
            this.materialTypeField = new List<string>();
            this.includedComponentsField = new List<string>();
            this.compatibleDevicesField = new List<string>();
            this.compatiblePhoneModelsField = new List<string>();
            this.specialSizeTypeField = new List<string>();
            this.specialFeaturesField = new List<string>();
            this.styleNameField = new List<string>();
            this.genreField = new List<string>();
            this.departmentNameField = new List<string>();
            this.certificateNumberField = new List<string>();
            this.certificateTypeField = new List<string>();
            this.variationDataField = new ThreeDPrintingVariationData();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CertificateType", DataType="normalizedString")]
        public List<string> CertificateType {
            get {
                return this.certificateTypeField;
            }
            set {
                this.certificateTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CertificateNumber", DataType="normalizedString")]
        public List<string> CertificateNumber {
            get {
                return this.certificateNumberField;
            }
            set {
                this.certificateNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DepartmentName", DataType="normalizedString")]
        public List<string> DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Genre", DataType="normalizedString")]
        public List<string> Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("StyleName", DataType="normalizedString")]
        public List<string> StyleName {
            get {
                return this.styleNameField;
            }
            set {
                this.styleNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecialFeatures", DataType="normalizedString")]
        public List<string> SpecialFeatures {
            get {
                return this.specialFeaturesField;
            }
            set {
                this.specialFeaturesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecialSizeType", DataType="normalizedString")]
        public List<string> SpecialSizeType {
            get {
                return this.specialSizeTypeField;
            }
            set {
                this.specialSizeTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CompatiblePhoneModels", DataType="normalizedString")]
        public List<string> CompatiblePhoneModels {
            get {
                return this.compatiblePhoneModelsField;
            }
            set {
                this.compatiblePhoneModelsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CompatibleDevices", DataType="normalizedString")]
        public List<string> CompatibleDevices {
            get {
                return this.compatibleDevicesField;
            }
            set {
                this.compatibleDevicesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("IncludedComponents", DataType="normalizedString")]
        public List<string> IncludedComponents {
            get {
                return this.includedComponentsField;
            }
            set {
                this.includedComponentsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaterialType", DataType="normalizedString")]
        public List<string> MaterialType {
            get {
                return this.materialTypeField;
            }
            set {
                this.materialTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SupportedDevices", DataType="normalizedString")]
        public List<string> SupportedDevices {
            get {
                return this.supportedDevicesField;
            }
            set {
                this.supportedDevicesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FinishType", DataType="normalizedString")]
        public List<string> FinishType {
            get {
                return this.finishTypeField;
            }
            set {
                this.finishTypeField = value;
            }
        }
    }
}
