// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AmazonMWSTester.Amazon</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonMWSTester.Amazon {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WineAndAlcohol {
        
        private WineAndAlcoholProductType productTypeField;
        
        private WineAndAlcoholVariationData variationDataField;
        
        private string bodyDescriptionField;
        
        private string nutritionFactsField;
        
        private decimal phValueField;
        
        private bool phValueFieldSpecified;
        
        private List<string> specialFeaturesField;
        
        private VolumeDimension itemVolumeField;
        
        private string agingVesselMaterialField;
        
        private System.DateTime bottledDateField;
        
        private bool bottledDateFieldSpecified;
        
        private string packageTypeNameField;
        
        private string cooperageHeadToastDesignationField;
        
        private bool isPerishableField;
        
        private bool isPerishableFieldSpecified;
        
        private string occasionTypeField;
        
        private string countryOfOriginField;
        
        private string regionOfOriginField;
        
        private string importerField;
        
        private string liquidPackagingTypeField;
        
        private bool isLiquidDoubleSealedField;
        
        private bool isLiquidDoubleSealedFieldSpecified;
        
        private string bottleTypeField;
        
        private DateIntegerDimension barrelAgingTimeField;
        
        private string awardsWonField;
        
        private string servingRecommendationField;
        
        private string countryStringField;
        
        private WeightDimension caffeineContentField;
        
        private string cooperageManufacturerField;
        
        private string primaryFermentationYeastField;
        
        private string specialIngredientsField;
        
        private string fermentationMethodField;
        
        private string secondaryFermentationTypeField;
        
        private VolumeDimension containerVolumeField;
        
        private bool isExpirationDatedProductField;
        
        private bool isExpirationDatedProductFieldSpecified;
        
        private string ageRangeDescriptionField;
        
        private AlcoholContentDimension alcoholContentField;
        
        private string cooperageMaterialField;
        
        private string containerMaterialTypeField;
        
        private string cuisineField;
        
        private decimal cooperageNewMaterialPercentageField;
        
        private bool cooperageNewMaterialPercentageFieldSpecified;
        
        private string externalTestingCertificationField;
        
        private string ingredientsField;
        
        private string filteringProcessField;
        
        private List<AllergenInformationType> allergenInformationField;
        
        private string subregionOfOriginField;
        
        private string directionsField;
        
        private string useByRecommendationField;
        
        private bool customerReturnPolicyFieldSpecified;
        
        private string containerTypeField;
        
        private string originDescriptionField;
        
        private string tasteDescriptionField;
        
        private string amountProducedField;
        
        private VolumeDimension itemDisplayVolumeField;
        
        private string cooperageToastLevelField;
        
        private string storageInstructionsField;
        
        private string colorMapField;
        
        private string closureTypeField;
        
        private DateIntegerDimension bottleAgingTimeField;
        
        private string specialtyField;
        
        private string liquidPackagingSealField;
        
        private bool oneClickAvailableField;
        
        private bool oneClickAvailableFieldSpecified;
        
    public WineAndAlcoholProductType ProductType {get; set;}

    public WineAndAlcoholVariationData VariationData {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BodyDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string NutritionFacts {get; set;}

    public decimal PhValue {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PhValueSpecified {get; set;}

    public VolumeDimension ItemVolume {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AgingVesselMaterial {get; set;}

    public System.DateTime BottledDate {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BottledDateSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PackageTypeName {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CooperageHeadToastDesignation {get; set;}

    public bool IsPerishable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPerishableSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OccasionType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CountryOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string RegionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Importer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LiquidPackagingType {get; set;}

    public bool IsLiquidDoubleSealed {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsLiquidDoubleSealedSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string BottleType {get; set;}

    public DateIntegerDimension BarrelAgingTime {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AwardsWon {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ServingRecommendation {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CountryString {get; set;}

    public WeightDimension CaffeineContent {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CooperageManufacturer {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PrimaryFermentationYeast {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SpecialIngredients {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FermentationMethod {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SecondaryFermentationType {get; set;}

    public VolumeDimension ContainerVolume {get; set;}

    public bool IsExpirationDatedProduct {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsExpirationDatedProductSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AgeRangeDescription {get; set;}

    public AlcoholContentDimension AlcoholContent {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CooperageMaterial {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ContainerMaterialType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Cuisine {get; set;}

    public decimal CooperageNewMaterialPercentage {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CooperageNewMaterialPercentageSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ExternalTestingCertification {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Ingredients {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string FilteringProcess {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string SubregionOfOrigin {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Directions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string UseByRecommendation {get; set;}

    public CustomerReturnPolicyType CustomerReturnPolicy {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomerReturnPolicySpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ContainerType {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OriginDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string TasteDescription {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string AmountProduced {get; set;}

    public VolumeDimension ItemDisplayVolume {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string CooperageToastLevel {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string StorageInstructions {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ColorMap {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ClosureType {get; set;}

    public DateIntegerDimension BottleAgingTime {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Specialty {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string LiquidPackagingSeal {get; set;}

    public bool OneClickAvailable {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OneClickAvailableSpecified {get; set;}

        
        public WineAndAlcohol() {
            this.bottleAgingTimeField = new DateIntegerDimension();
            this.itemDisplayVolumeField = new VolumeDimension();
            this.allergenInformationField = new List<AllergenInformationType>();
            this.alcoholContentField = new AlcoholContentDimension();
            this.containerVolumeField = new VolumeDimension();
            this.barrelAgingTimeField = new DateIntegerDimension();
            this.itemVolumeField = new VolumeDimension();
            this.specialFeaturesField = new List<string>();
            this.variationDataField = new WineAndAlcoholVariationData();
            this.productTypeField = new WineAndAlcoholProductType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SpecialFeatures", DataType="normalizedString")]
        public List<string> SpecialFeatures {
            get {
                return this.specialFeaturesField;
            }
            set {
                this.specialFeaturesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AllergenInformation")]
        public List<AllergenInformationType> AllergenInformation {
            get {
                return this.allergenInformationField;
            }
            set {
                this.allergenInformationField = value;
            }
        }
    }
}
